import { useEffect, useMemo, useState } from "react";
import { Bot, Search, ShieldCheck } from "lucide-react";
import { listDevices, type Device } from "@/lib/devices";
import { createCatalogAction, proposeWithAi, searchCommands, type CatalogItem } from "@/lib/commandCatalog";

const vendorOf = (device?: Device) => device?.type === "linux_edge" ? "linux" : device?.type === "generic_firewall" || device?.type === "generic_syslog_source" ? "generic" : device?.type ?? "";
export default function CommandCatalogPanel() {
  const [devices, setDevices] = useState<Device[]>([]); const [deviceId, setDeviceId] = useState(""); const [q, setQ] = useState(""); const [vendor, setVendor] = useState(""); const [category, setCategory] = useState(""); const [riskLevel, setRisk] = useState(""); const [readOnly, setReadOnly] = useState(false); const [executable, setExecutable] = useState(false); const [items, setItems] = useState<CatalogItem[]>([]); const [params, setParams] = useState<Record<string, Record<string, string>>>({}); const [message, setMessage] = useState(""); const [aiText, setAiText] = useState(""); const [loading, setLoading] = useState(false);
  const selected = useMemo(() => devices.find((d) => d.id === deviceId), [devices, deviceId]);
  useEffect(() => { void listDevices().then(setDevices).catch((e) => setMessage(e.message)); }, []);
  useEffect(() => { setLoading(true); const handle = window.setTimeout(() => void searchCommands({ q, vendor, category, riskLevel, readOnly: readOnly ? "true" : "", executable: executable ? "true" : "" }).then((r) => setItems(r.items)).catch((e) => setMessage(e.message)).finally(() => setLoading(false)), 180); return () => window.clearTimeout(handle); }, [q, vendor, category, riskLevel, readOnly, executable]);
  useEffect(() => { if (selected) setVendor(vendorOf(selected)); }, [selected]);
  const categories = [...new Set(items.map((x) => x.category))];
  const create = async (item: CatalogItem) => { if (!deviceId) return setMessage("ابتدا دستگاه هدف را انتخاب کنید."); try { await createCatalogAction(item.id, deviceId, params[item.id] ?? {}); setMessage("برنامه اجرا ساخته شد؛ برای بازبینی و تأیید به مرکز عملیات بروید."); } catch (e) { setMessage(e instanceof Error ? e.message : "ساخت برنامه اجرا ناموفق بود."); } };
  const askAi = async () => { if (!aiText.trim()) return; try { await proposeWithAi(aiText, vendor || "generic", deviceId || undefined); setMessage("پیشنهاد هوش مصنوعی فقط به‌صورت برنامهٔ پیشنهادی ساخته شد و اجرا نشده است."); } catch (e) { setMessage(e instanceof Error ? e.message : "ساخت پیشنهاد ناموفق بود."); } };
  return <section dir="rtl" className="mb-5 rounded-2xl border border-cyan-900/60 bg-slate-950/80 p-5 text-right text-slate-100">
    <div className="mb-4 flex items-center gap-2"><ShieldCheck className="text-cyan-400"/><div><h2 className="text-xl font-bold">دستورات آماده</h2><p className="text-sm text-slate-400">ابتدا دستگاه را انتخاب کنید، سپس یک عملیات کنترل‌شده بسازید.</p></div></div>
    <div className="grid gap-3 md:grid-cols-4"><select value={deviceId} onChange={(e)=>setDeviceId(e.target.value)} className="rounded-lg border border-slate-700 bg-slate-900 p-2"><option value="">انتخاب دستگاه</option>{devices.map(d=><option key={d.id} value={d.id}>{d.name}</option>)}</select><div className="relative"><Search className="absolute right-2 top-2.5 h-4 w-4 text-slate-500"/><input value={q} onChange={e=>setQ(e.target.value)} placeholder="جستجوی دستور فارسی" className="w-full rounded-lg border border-slate-700 bg-slate-900 py-2 pl-2 pr-8"/></div><select value={vendor} onChange={e=>setVendor(e.target.value)} className="rounded-lg border border-slate-700 bg-slate-900 p-2"><option value="">همه وندورها</option>{["linux","mikrotik","fortigate","cisco","pfsense","generic"].map(v=><option key={v}>{v}</option>)}</select><select value={riskLevel} onChange={e=>setRisk(e.target.value)} className="rounded-lg border border-slate-700 bg-slate-900 p-2"><option value="">همه ریسک‌ها</option><option value="low">کم</option><option value="medium">متوسط</option><option value="high">زیاد</option><option value="critical">بحرانی</option></select></div>
    <div className="my-3 flex flex-wrap gap-4 text-sm"><label><input type="checkbox" checked={readOnly} onChange={e=>setReadOnly(e.target.checked)}/> فقط خواندنی</label><label><input type="checkbox" checked={executable} onChange={e=>setExecutable(e.target.checked)}/> قابل اجرا</label>{categories.length>0&&<select value={category} onChange={e=>setCategory(e.target.value)} className="bg-slate-900"><option value="">همه دسته‌ها</option>{categories.map(c=><option key={c}>{c}</option>)}</select>}</div>
    {message&&<p className="mb-3 rounded-lg bg-cyan-950/50 p-3 text-sm text-cyan-200">{message}</p>}
    <div className="grid gap-3 md:grid-cols-2 xl:grid-cols-3">{items.map(item=><article key={item.id} className="rounded-xl border border-slate-800 bg-slate-900/70 p-4"><div className="flex justify-between gap-2"><h3 className="font-bold">{item.titleFa}</h3><span className="text-xs text-cyan-400">{item.uiHints.badgeFa}</span></div><p className="mt-2 text-sm text-slate-400">{item.descriptionFa}</p>{item.requiredParams.map(field=><input key={field.key} placeholder={field.labelFa} value={params[item.id]?.[field.key]??""} onChange={e=>setParams(p=>({...p,[item.id]:{...p[item.id],[field.key]:e.target.value}}))} className="mt-2 w-full rounded border border-slate-700 bg-slate-950 p-2 text-sm"/>)}<button onClick={()=>void create(item)} className="mt-3 rounded-lg bg-cyan-700 px-3 py-2 text-sm hover:bg-cyan-600">ساخت برنامه اجرا</button></article>)}</div>
    {!loading&&items.length===0&&<div className="mt-4 rounded-xl border border-dashed border-slate-700 p-4"><p>دستور مناسبی پیدا نشد. درخواست را برای ساخت پیشنهاد سفارشی بنویسید.</p><div className="mt-2 flex gap-2"><input value={aiText} onChange={e=>setAiText(e.target.value)} className="min-w-0 flex-1 rounded border border-slate-700 bg-slate-900 p-2" placeholder="درخواست عملیاتی شما"/><button onClick={()=>void askAi()} className="flex items-center gap-1 rounded bg-violet-700 px-3"><Bot className="h-4 w-4"/> ساخت با هوش مصنوعی</button></div></div>}
  </section>;
}
