import type { Client, ClientChannel } from "ssh2";
import { BackupError } from "./backup-collector.js";
import { trackCurrentApplicationSshCommand } from "../security/application-command-provenance.js";
// Legacy SCP destination protocol: FortiGate virtual files and IOS flash support it.
// Paths/names must be generated by the registered restore handler, not supplied by users.
export function sendScpFile(client: Client, destination: string, content: Buffer, filename: string): Promise<void> {
  if (!/^(?:fgt-restore-config|flash:\/soar-[a-f0-9]{32}\.cfg)$/.test(destination) || !/^soar-[a-f0-9]{32}\.(?:cfg|conf)$/.test(filename)) {
    return Promise.reject(new BackupError("RESTORE_UNSAFE_PATH"));
  }
  return new Promise((resolve, reject) => {
    let channel: ClientChannel | undefined, settled = false, phase = 0, pending = Buffer.alloc(0);
    const finish = (error?: Error) => {
      if (settled) return; settled = true; clearTimeout(timer);
      if (error) { channel?.close(); reject(error); } else { channel?.end(); resolve(); }
    };
    const timer = setTimeout(() => finish(new BackupError("RESTORE_TRANSFER_TIMEOUT", 504)), 120000);
    client.exec("scp -t " + destination, (error, stream) => {
      if (error) return finish(new BackupError("RESTORE_SCP_REQUIRED", 502));
      channel = stream;
      if (settled) { stream.close(); return; }
      stream.stderr.on("data", () => finish(new BackupError("RESTORE_SCP_REQUIRED", 502)));
      stream.on("error", () => finish(new BackupError("RESTORE_TRANSFER_FAILED", 502)));
      stream.on("close", () => { if (!settled) finish(new BackupError("RESTORE_TRANSFER_UNCONFIRMED", 502)); });
      stream.on("data", (chunk: Buffer) => {
        if (settled) return;
        if (pending.length + chunk.length > 65536) return finish(new BackupError("RESTORE_TRANSFER_REJECTED", 502));
        pending = Buffer.concat([pending, Buffer.from(chunk)]);
        while (pending.length && !settled) {
          if (pending[0] !== 0) return finish(new BackupError("RESTORE_TRANSFER_REJECTED", 502));
          pending = pending.subarray(1);
          if (phase === 0) { phase = 1; stream.write("C0600 " + content.length + " " + filename + "\n"); }
          else if (phase === 1) { phase = 2; stream.write(content); stream.write(Buffer.from([0])); }
          else if (phase === 2) { phase = 3; finish(); }
        }
      });
    });
  });
}
export function writeSftpFile(client: Client, path: string, content: Buffer): Promise<void> {
  if (!/^soar-[a-f0-9]{32}\.rsc$/.test(path)) return Promise.reject(new BackupError("RESTORE_UNSAFE_PATH"));
  return new Promise((resolve, reject) => {
    let settled = false;
    const timer = setTimeout(() => finish(new BackupError("RESTORE_TRANSFER_TIMEOUT", 504)), 120000);
    let sftp: import("ssh2").SFTPWrapper | undefined;
    const finish = (error?: Error) => { if (settled) return; settled = true; clearTimeout(timer); sftp?.end(); error ? reject(error) : resolve(); };
    client.sftp((error, channel) => {
      if (error) return finish(new BackupError("RESTORE_SFTP_REQUIRED", 502));
      sftp = channel; if (settled) { channel.end(); return; }
      channel.on("error", () => finish(new BackupError("RESTORE_TRANSFER_FAILED", 502)));
      channel.on("close", () => { if (!settled) finish(new BackupError("RESTORE_TRANSFER_UNCONFIRMED", 502)); });
      channel.writeFile(path, content, { mode: 0o600, flag: "wx" }, error => finish(error ? new BackupError("RESTORE_TRANSFER_FAILED", 502) : undefined));
    });
  });
}
export function runRestoreCommand(client: Client, command: string, stdin?: Buffer): Promise<Buffer> {
  return trackCurrentApplicationSshCommand(command, () => new Promise((resolve, reject) => {
    let settled = false, channel: ClientChannel | undefined, size = 0, stderr = false;
    const chunks: Buffer[] = [];
    const finish = (error?: Error) => { if (settled) return; settled = true; clearTimeout(timer); if (error) { channel?.close(); reject(error); } else resolve(Buffer.concat(chunks)); };
    const timer = setTimeout(() => finish(new BackupError("RESTORE_APPLY_TIMEOUT", 504)), 180000);
    client.exec(command, (error, stream) => {
      if (error) return finish(new BackupError("RESTORE_COMMAND_FAILED", 502));
      channel = stream; if (settled) { stream.close(); return; }
      stream.on("data", (chunk: Buffer) => { if (settled) return; size += chunk.length; if (size > 256 * 1024) return finish(new BackupError("RESTORE_OUTPUT_LIMIT", 502)); chunks.push(Buffer.from(chunk)); });
      stream.stderr.on("data", () => { stderr = true; });
      stream.on("error", () => finish(new BackupError("RESTORE_COMMAND_FAILED", 502)));
      stream.on("close", (code: number | undefined) => {
        const result = Buffer.concat(chunks).toString("utf8");
        if (code !== 0 || stderr || /failure:|syntax error|bad command|not enough permissions|error:|Command fail|% Invalid/i.test(result)) return finish(new BackupError("RESTORE_COMMAND_FAILED", 502));
        finish();
      });
      if (stdin) stream.end(stdin); else stream.end();
    });
  }));
}
