import type { CompanyStatusEquipment, CompanyStatusReport } from "./company-status-report.types.js";

function reportCss(font: string) { return `
@font-face{font-family:IRANYekan;src:url("data:font/ttf;base64,${font}") format("truetype")}
*{box-sizing:border-box}body{margin:0;background:#e9edf2;color:#102b52;font:14px/1.5 IRANYekan,Tahoma,sans-serif;overflow-wrap:anywhere}
.page{width:210mm;height:297mm;margin:0 auto 12px;background:#fff;padding:8mm;display:flex;flex-direction:column;page-break-after:always}.page:last-child{page-break-after:auto}
h1,h2,h3,p{margin:0}h1{font-size:24px;line-height:1.45;color:#102653}h2{font-size:17px;margin-bottom:5px}h3{font-size:14px}small{font-size:11px;color:#536d8e}
.head{display:grid;grid-template-columns:42mm 1fr 55mm;gap:5mm;align-items:center;border-bottom:2px solid #17376b;padding-bottom:4mm;margin-bottom:4mm}.brand{font:bold 15px/1.25 Tahoma,sans-serif;color:#102653}.brand small{display:block;font:11px IRANYekan;color:#627d9f}.head h1{font-size:22px;text-align:center;background:linear-gradient(135deg,#e8f1ff,#dce8fb);border-radius:9px;padding:10px 8px}.head p{text-align:center;font-size:13px;margin-top:3px}.meta{display:grid;gap:4px;font-size:11px}.meta span{display:grid;grid-template-columns:54px 1fr;gap:4px;align-items:center}.meta b,.meta bdi{background:#fff;border:1px solid #9cb9dd;border-radius:4px;padding:3px 5px;min-height:22px}
.summary{display:grid;grid-template-columns:repeat(5,1fr);gap:6px;margin-bottom:4mm}.summary div{background:#f7faff;border:1px solid #bfd3ea;border-radius:7px;padding:5px;text-align:center}.summary strong{display:block;font-size:21px;line-height:1.3}.summary span{font-size:11px}.active{color:#217b56}.limited{color:#986320}.inactive{color:#b13a45}
.vendor-summary{border:1px solid #b8cde6;border-radius:8px;margin-bottom:4mm}.vendor-summary h2{background:#edf4fc;padding:6px 9px;margin:0}.vendor-summary table{width:100%;border-collapse:collapse;font-size:10px}.vendor-summary th,.vendor-summary td{padding:4px 5px;border-bottom:1px solid #d8e4f1;text-align:center}.vendor-summary th:first-child,.vendor-summary td:first-child{text-align:right}.vendor-summary tr:last-child td{border-bottom:0}
.equipment{display:grid;gap:7px}.equipment h2{margin-bottom:0}.device{display:grid;grid-template-columns:31mm 1fr;border:1px solid #2778c8;border-radius:9px;padding:0;break-inside:avoid;background:#fff}.device:before{content:attr(data-vendor);display:flex;align-items:center;justify-content:center;text-align:center;font-weight:900;font-size:15px;color:#2778c8;background:#eaf4ff;padding:8px}.device header,.device .identity,.device .reason,.device .facts,.device footer{grid-column:2}.device header{display:flex;justify-content:space-between;gap:8px;align-items:center;padding:6px 9px 0}.device .identity{display:flex;justify-content:space-between;gap:8px;padding:0 9px;font-size:11px;color:#4e6b8e}.device .reason{font-size:12px;margin:2px 9px}.device .facts{display:flex;gap:10px;flex-wrap:wrap;padding:0 9px 4px;font-size:11px}.device footer{border-top:1px solid #e1e9f2;padding:4px 9px;font-size:10px;color:#607284}.state{font-size:10px;background:#f0f4f8;border-radius:4px;padding:2px 6px;white-space:nowrap}.host{font:12px Tahoma,sans-serif;color:#173d6c}.omission{font-size:11px;background:#f2f6fa;border:1px solid #d7e2ed;border-radius:5px;padding:4px 7px;margin-top:5px}.empty{padding:15px;border:1px dashed #b6c8dc;color:#536d8e}
.device[data-category="firewall"]{border-color:#d3636b}.device[data-category="firewall"]:before{background:#fff0f1;color:#ad333e}.device[data-category="switch"]{border-color:#51ab81}.device[data-category="switch"]:before{background:#e9f8ef;color:#176e45}.device[data-category="router"]{border-color:#e7a84f}.device[data-category="router"]:before{background:#fff5e6;color:#ac660f}.device[data-category="other"]{border-color:#9083c9}.device[data-category="other"]:before{background:#f4f0ff;color:#6655a0}
.page-footer{display:flex;justify-content:space-between;gap:10px;margin-top:auto;padding-top:6px;border-top:1px solid #cbd9e8;font-size:10px;color:#627995}.followup-head{display:flex;justify-content:space-between;align-items:center;margin-bottom:4mm}.legend{border:1px solid #9db6d3;background:#f3f7fc;border-right:4px solid #466b98;border-radius:6px;padding:8px 10px;margin-bottom:4mm;font-size:13px}.legend p{margin-top:2px}.issues{display:grid;gap:7px}.issue{border:1px solid #c5d6e8;border-radius:7px;padding:7px 9px;break-inside:avoid}.issue header{display:flex;gap:7px;align-items:center;margin-bottom:3px}.issue h3{flex:1;font-size:14px}.issue h3 small{display:block;font-size:10px}.issue p{font-size:12px;margin-bottom:3px}.issue footer{font-size:10px;color:#496b90}.number{display:grid;place-items:center;width:22px;height:22px;border-radius:50%;background:#eaf1f8;color:#365a80}.actions{display:grid;grid-template-columns:1fr 1fr;gap:8px;margin-top:4mm}.actions section{border:1px solid #c7d7e8;border-radius:6px;padding:7px}.actions h2{font-size:13px}.actions ul{padding-right:16px;margin:0;font-size:11px}.signature{display:flex;gap:7px;align-items:center;margin-top:4mm;font-size:11px}.signature span{margin-right:auto;color:#647c96}
.meta{font-size:12px}.meta span{grid-template-columns:72px 1fr}.head h1{font-size:24px}.head p{font-size:14px}
.summary div{padding:8px 5px}.summary strong{font-size:24px}.summary span{font-size:12px}
.vendor-summary table{font-size:12px}.vendor-summary th,.vendor-summary td{padding:6px 5px}
.device{min-height:30mm}.device:before{font-size:19px}.device header{padding:9px 11px 0}.device h3{font-size:16px}.device .identity{font-size:13px;padding:0 11px}.device .reason{font-size:13px;margin:4px 11px}.device .facts{font-size:13px;gap:12px;padding:2px 11px 7px}.device footer{font-size:11px;padding:6px 11px}.state{font-size:12px}.host{font-size:13px}.omission,.page-footer{font-size:12px}
.issue{padding:11px 13px}.issue h3{font-size:16px}.issue h3 small,.issue footer{font-size:12px}.issue p,.actions ul,.signature{font-size:13px}.actions h2{font-size:15px}.actions section{padding:10px}
@page{size:A4;margin:0}@media print{body{background:#fff}.page{margin:0}}
`; }

const esc = (value: unknown) => String(value ?? "").replace(/[&<>"\u0027]/g, c => ({ "&": "&amp;", "<": "&lt;", ">": "&gt;", "\"": "&quot;", "\u0027": "&#39;" })[c]!);
const short = (text: string | undefined, n: number) => esc(text && text.length > n ? text.slice(0, n - 1) + "…" : text || "ثبت نشده");
export const reportStateLabels = { active: "بدون هشدار", limited: "نیازمند بررسی", inactive: "قطع کانال" } as const;
export const reportCategoryLabels = { server: "سرور", firewall: "فایروال", switch: "سوئیچ", router: "روتر", other: "سایر" } as const;
const date = (value: string | null) => value && Number.isFinite(Date.parse(value)) ? new Date(value).toLocaleString("fa-IR", { timeZone: "Asia/Tehran" }) : "زمان نامشخص";
const percent = (n: number | null) => n === null ? "—" : `${n.toLocaleString("fa-IR", { maximumFractionDigits: 1 })}٪`;
const connectionLabel = (state: CompanyStatusEquipment["connectionState"]) => state === "online" ? "برقرار" : state === "offline" ? "قطع" : state === "auth_failed" ? "ورود رد شد" : "تأیید نشده";
const source = (e: CompanyStatusEquipment, report: CompanyStatusReport) => `${e.source === "live" ? "زنده" : e.source === "snapshot" ? "ذخیره‌شده" : "موجودی"} · ${date(e.collectedAt)}${e.collectedAt && Date.parse(report.generatedAt)-Date.parse(e.collectedAt)>900000 ? " · دادهٔ قدیمی" : ""}`;
export function selectReportDetails(report: CompanyStatusReport) {
  const rank = { inactive: 0, limited: 1, active: 2 };
  const ordered = [...report.equipment].sort((a,b)=>rank[a.status]-rank[b.status]);
  const vendorCount = new Set(report.equipment.map(e=>e.vendor)).size;
  return { overview: ordered.slice(0, vendorCount > 4 ? 2 : 4), issues: ordered.filter(e=>e.status !== "active").slice(0, 2) };
}
const average = (rows: CompanyStatusEquipment[], key: "cpuPercent"|"diskPercent") => { const values=rows.map(e=>e[key]).filter((v): v is number=>v!==null); return values.length ? `${(values.reduce((a,b)=>a+b,0)/values.length).toLocaleString("fa-IR",{maximumFractionDigits:1})}٪` : "—"; };


export function renderReadableReportHtml(report: CompanyStatusReport, font: string) {
  const selection = selectReportDetails(report);
  const vendorNames = [...new Set(report.equipment.map(e=>e.vendor))];
  const stats = vendorNames.map(v=>{ const rows=report.equipment.filter(e=>e.vendor===v); return { vendor:v, rows, total:rows.length, active:rows.filter(e=>e.status==="active").length, limited:rows.filter(e=>e.status==="limited").length, inactive:rows.filter(e=>e.status==="inactive").length, online:rows.filter(e=>e.connectionState==="online").length, cpu:average(rows,"cpuPercent"), disk:average(rows,"diskPercent") }; });
  const statRows = stats.slice(0,8).map(s=>`<tr><th>${esc(s.vendor)}</th><td>${s.total.toLocaleString("fa-IR")}</td><td class="active">${s.active.toLocaleString("fa-IR")}</td><td class="limited">${s.limited.toLocaleString("fa-IR")}</td><td class="inactive">${s.inactive.toLocaleString("fa-IR")}</td><td>${s.online.toLocaleString("fa-IR")}</td><td>${s.cpu}</td><td>${s.disk}</td></tr>`).join("");
  const cards = selection.overview.map(e=>`<article class="device" data-device="${esc(e.id)}" data-category="${e.category}" data-vendor="${reportCategoryLabels[e.category]}"><header><h3>${esc(e.name)}</h3><strong class="state ${e.status}">${reportStateLabels[e.status]}</strong></header><div class="identity"><span>${esc(e.vendor)} · ${short(e.model,45)}</span><bdi class="host">${esc(e.host)}</bdi></div>${e.status!=="active" ? `<p class="reason">${short(e.statusReason || e.description,100)}</p>` : ""}<div class="facts">${e.category==="server" || e.cpuPercent!==null ? `<span>CPU: <b>${percent(e.cpuPercent)}</b></span>` : ""}${e.category==="server" ? `<span>Disk: <b>${percent(e.diskPercent)}</b></span>` : ""}<span>اتصال: <b>${connectionLabel(e.connectionState)}</b></span>${e.vendorFields.slice(0,2).map(f=>`<span>${short(f.label,18)}: <bdi>${short(f.value,34)}</bdi></span>`).join("")}</div><footer>${source(e,report)}</footer></article>`).join("") || `<p class="empty">تجهیزی ثبت نشده است.</p>`;
  const issues = selection.issues.map((e,i)=>`<article class="issue"><header><span class="number">${(i+1).toLocaleString("fa-IR")}</span><h3>${esc(e.name)} <small>${esc(e.vendor)} · <bdi>${esc(e.host)}</bdi></small></h3><strong class="${e.status}">${reportStateLabels[e.status]}</strong></header><p><b>علت:</b> ${short(e.statusReason || e.description,220)}</p><p><b>قدم بعدی:</b> ${short(e.recommendation,250)}</p><footer>${e.connectionState==="online" ? "اتصال برقرار است؛ سنسور و هشدار بررسی شود." : "تنظیم اتصال و تست کانال مدیریتی بررسی شود."}</footer></article>`).join("") || `<p class="empty">مورد نیازمند بررسی ثبت نشده است.</p>`;
  const linesFor = (values: string[]) => values.length ? values.slice(0,3).map(v=>`<li>${short(v,110)}</li>`).join("") : "<li>—</li>";
  return `<!doctype html><html lang="fa" dir="rtl"><head><meta charset="utf-8"><title>${esc(report.company.name)} - گزارش وضعیت</title><style>${reportCss(font)}</style></head><body><section class="page">
  <header class="head"><div><span class="brand">IT Infrastructure<small>Report Form</small></span></div><div><h1>فرم گزارش کار تجهیزات زیرساخت IT</h1><p>وضعیت تجهیزات شرکت ${esc(report.company.name)}</p></div><div class="meta"><span>تاریخ شمسی:<b>${esc(report.reportDateFa)}</b></span><span>تاریخ میلادی:<bdi><b>${esc(report.reportDateGregorian)}</b></bdi></span><span>ساعت:<b>${esc(report.reportTime)}</b></span><span>شماره:<b>${esc(report.reportNumber)}</b></span><span>تهیه‌کننده:<b>${short(report.preparedBy,35)}</b></span></div></header>
  <div class="summary"><div><strong>${report.summary.total.toLocaleString("fa-IR")}</strong><span>کل تجهیزات</span></div><div><strong class="active">${report.summary.active.toLocaleString("fa-IR")}</strong><span>بدون هشدار</span></div><div><strong class="limited">${report.summary.limited.toLocaleString("fa-IR")}</strong><span>نیازمند بررسی</span></div><div><strong class="inactive">${report.summary.inactive.toLocaleString("fa-IR")}</strong><span>قطع کانال</span></div><div><strong>${report.summary.healthScore.toLocaleString("fa-IR")}%</strong><span>سهم بدون هشدار</span></div></div>
  <section class="vendor-summary"><h2>خلاصه آماری وندورها</h2><table><thead><tr><th>وندور</th><th>کل</th><th>بدون هشدار</th><th>بررسی</th><th>قطع</th><th>آنلاین</th><th>میانگین CPU</th><th>میانگین Disk</th></tr></thead><tbody>${statRows || `<tr><td colspan="8">—</td></tr>`}</tbody></table>${vendorNames.length>8 ? `<p class="omission">${(vendorNames.length-8).toLocaleString("fa-IR")} وندور دیگر در فایل Excel</p>` : ""}</section>
  <section class="equipment"><h2>وضعیت تجهیزات</h2>${cards}</section>${report.equipment.length>selection.overview.length ? `<p class="omission">فهرست کامل: ${(report.equipment.length-selection.overview.length).toLocaleString("fa-IR")} تجهیز دیگر در شیت «تجهیزات» Excel</p>` : ""}
  <footer class="page-footer"><bdi>${esc(report.reportNumber)}</bdi><span>۱ / ۲</span></footer></section>
  <section class="page"><header class="followup-head"><h1>موارد نیازمند بررسی</h1><span>${esc(report.company.name)} · ${esc(report.reportDateFa)} · ${esc(report.reportTime)}</span></header>
  <aside class="legend"><b>«نیازمند بررسی» یعنی چه؟</b><p>تجهیز ممکن است آنلاین باشد اما هشدار، سنسور ناقص یا دادهٔ ناکافی داشته باشد؛ این برچسب به‌تنهایی نفوذ یا خرابی قطعی را ثابت نمی‌کند.</p></aside>
  <section class="issues">${issues}</section>${report.equipment.filter(e=>e.status!=="active").length>selection.issues.length ? `<p class="omission">سایر علت‌ها و راهکارها در فایل Excel</p>` : ""}
  <div class="actions"><section><h2>اقدامات انجام‌شده</h2><ul>${linesFor(report.completedActions)}</ul></section><section><h2>اقدامات بعدی</h2><ul>${linesFor(report.futureActions)}</ul></section></div>
  <div class="signature">مسئول: <b>${short(report.responsibleName,55)}</b><span>جزئیات همه تجهیزات: فایل Excel</span></div><footer class="page-footer"><span>«—» یعنی داده موجود نیست.</span><span>۲ / ۲</span></footer></section></body></html>`;
}
