import type { CompanyStatusEquipment, CompanyStatusReport } from "./company-status-report.types.js";

function reportCss(font: string) { return `
@font-face{font-family:IRANYekan;src:url(data:font/ttf;base64,${font}) format('truetype')}
*{box-sizing:border-box}body{margin:0;background:#eef2f6;color:#26374a;font:14px/1.65 IRANYekan,Tahoma,sans-serif;overflow-wrap:anywhere}
.page{width:210mm;height:297mm;margin:0 auto 12px;background:#fff;padding:9mm 10mm;display:flex;flex-direction:column;page-break-after:always}.page:last-child{page-break-after:auto}
h1,h2,h3,p{margin:0}h1{font-size:23px;line-height:1.6;color:#183454}h2{font-size:16px;margin-bottom:5px}h3{font-size:15px}small{font-size:12px;font-weight:normal;color:#586a7d}
.head{display:grid;grid-template-columns:1fr 58mm;gap:6mm;border-bottom:2px solid #304d68;padding-bottom:4mm;margin-bottom:4mm}.brand{font-size:12px;color:#586d81}.head p{font-size:13px;margin-top:4px}.meta{display:grid;gap:3px;font-size:12px;background:#f4f7fa;border-radius:7px;padding:9px;overflow-wrap:anywhere}
.summary{display:grid;grid-template-columns:repeat(4,1fr);gap:8px;margin-bottom:4mm}.summary div{background:#f5f8fb;border:1px solid #d9e2ea;border-radius:7px;padding:7px;text-align:center}.summary strong{display:block;font-size:23px;line-height:1.4}.summary span{font-size:12px}
.active{color:#28634f}.limited{color:#88612c}.inactive{color:#983c42}.vendor-summary{margin-bottom:4mm}table{width:100%;border-collapse:collapse;font-size:12px}th,td{padding:3px 8px;border-bottom:1px solid #dee6ec;text-align:right}thead{background:#eff4f8}tbody th{font-weight:normal}
.equipment{display:grid;gap:8px}.equipment h2{margin-bottom:0}.equipment h2 small{margin-right:10px}.device{border:1px solid #d3dfe8;border-radius:8px;padding:9px 12px;break-inside:avoid}.device header{display:flex;justify-content:space-between;gap:12px;align-items:center}.state{font-size:12px;background:#f3f6f8;border-radius:5px;padding:2px 7px;white-space:nowrap}
.identity{display:flex;justify-content:space-between;gap:12px;font-size:12px;color:#586a7d}.host{font:13px/1.7 Tahoma,sans-serif;color:#314c64}.reason{font-size:14px;margin:3px 0;line-height:1.7}.facts{display:flex;gap:16px;flex-wrap:wrap;font-size:12px}.device footer{font-size:11px;color:#607284;margin-top:5px;border-top:1px solid #e4ebf0;padding-top:3px}
.page-footer{display:flex;justify-content:space-between;gap:10px;margin-top:auto;padding-top:8px;border-top:1px solid #d9e2ea;font-size:11px;color:#5f7386;overflow-wrap:anywhere}.omission{font-size:12px;background:#f4f7fa;border-radius:6px;padding:5px 8px;margin-top:8px}.empty{padding:24px;border:1px dashed #c2d0de;color:#586a7d}
.followup-head{display:flex;align-items:center;justify-content:space-between;margin-bottom:4mm}.followup-head span{font-size:12px}.legend{background:#f3f6f9;border-right:3px solid #657e96;border-radius:6px;padding:10px 12px;margin-bottom:4mm;font-size:13px}.legend p{margin-top:3px}
.issues{display:grid;gap:10px}.issue{border:1px solid #d5dfe7;border-radius:8px;padding:10px 12px;break-inside:avoid}.issue header{display:flex;gap:8px;align-items:center;margin-bottom:5px}.issue h3{flex:1}.issue h3 small{display:block}.issue header>strong{font-size:12px}.number{display:grid;place-items:center;width:25px;height:25px;border-radius:50%;background:#eef3f7;color:#36546e}.issue p{font-size:14px;margin-bottom:5px}.issue footer{font-size:12px;color:#385d7d}
.actions{display:grid;grid-template-columns:1fr 1fr;gap:12px;margin-top:4mm}.actions section{border:1px solid #d5dfe7;border-radius:7px;padding:10px}.actions h2{font-size:14px}.actions ul{padding-right:18px;margin:0;font-size:12px}.notes{margin-top:10px;padding:10px;border:1px solid #d5dfe7;border-radius:6px;font-size:12px}.signature{display:flex;gap:8px;align-items:center;margin-top:4mm;font-size:12px}.signature span{margin-right:auto;color:#5f7386}
@page{size:A4;margin:0}@media print{body{background:white}.page{margin:0}}
`; }

const esc = (value: unknown) => String(value ?? "").replace(/[&<>"']/g, c => ({ "&": "&amp;", "<": "&lt;", ">": "&gt;", '"': "&quot;", "'": "&#39;" })[c]!);
const short = (text: string | undefined, n: number) => esc(text && text.length > n ? text.slice(0, n - 1) + "…" : text || "ثبت نشده");
export const reportStateLabels = { active: "بدون هشدار گزارش‌شده", limited: "نیازمند بررسی", inactive: "قطع کانال مدیریتی" } as const;
export const reportCategoryLabels = { server: "سرور", firewall: "فایروال", switch: "سوئیچ", router: "روتر", other: "سایر" } as const;
const date = (value: string | null) => value && Number.isFinite(Date.parse(value)) ? new Date(value).toLocaleString("fa-IR", { timeZone: "Asia/Tehran" }) : "زمان نامشخص";
const percent = (n: number | null) => n === null ? "داده موجود نیست" : `${n.toLocaleString("fa-IR", { maximumFractionDigits: 1 })}٪`;
export function selectReportDetails(report: CompanyStatusReport) {
  const rank = { inactive: 0, limited: 1, active: 2 };
  const ordered = [...report.equipment].sort((a,b)=>rank[a.status]-rank[b.status]);
  const vendorCount = new Set(report.equipment.map(e=>e.vendor)).size;
  return { overview: ordered.slice(0, vendorCount > 4 ? 2 : 4), issues: ordered.filter(e=>e.status !== "active").slice(0, 2) };
}

export function renderReadableReportHtml(report: CompanyStatusReport, font: string) {
  const selection=selectReportDetails(report);
  const vendorNames=[...new Set(report.equipment.map(e=>e.vendor))];
  const vendors=vendorNames.slice(0, 8).map(v=>{const rows=report.equipment.filter(e=>e.vendor===v);return `<tr><th>${esc(v)}</th><td>${rows.length.toLocaleString("fa-IR")}</td><td>${rows.filter(e=>e.status==="active").length.toLocaleString("fa-IR")}</td><td>${rows.filter(e=>e.status==="limited").length.toLocaleString("fa-IR")}</td><td>${rows.filter(e=>e.status==="inactive").length.toLocaleString("fa-IR")}</td></tr>`;}).join("");
  const measurement=(e: CompanyStatusEquipment) => `${e.source === "live" ? "جمع‌آوری زنده" : e.source === "snapshot" ? "نمونهٔ ذخیره‌شده؛ نه تست زنده" : "فقط موجودی؛ بدون سنجش"} · ${date(e.collectedAt)}${e.collectedAt && Date.parse(report.generatedAt)-Date.parse(e.collectedAt)>900000 ? " · دادهٔ قدیمی" : ""}`;
  const cards=selection.overview.map(e=>`<article class="device" data-device="${esc(e.id)}"><header><h3>${esc(e.name)}</h3><strong class="state ${e.status}">${reportStateLabels[e.status]}</strong></header><div class="identity"><span>${esc(e.vendor)} · ${reportCategoryLabels[e.category]} · ${short(e.model,50)}</span><bdi class="host">${esc(e.host)}</bdi></div><p class="reason">${short(e.statusReason || e.description,190)}</p>${e.description && e.description !== e.statusReason ? `<p class="editor-note">یادداشت: ${short(e.description,80)}</p>` : ""}<div class="facts">${e.cpuPercent !== null || e.category === "server" ? `<span>پردازنده (CPU): <b>${percent(e.cpuPercent)}</b></span>` : ""}${e.category === "server" ? `<span>دیسک: <b>${percent(e.diskPercent)}</b></span>` : ""}${e.vendorFields.slice(0,2).map(f=>`<span>${short(f.label,20)}: <bdi>${short(f.value,42)}</bdi></span>`).join("")}${e.physicalLocation ? `<span>محل: ${short(e.physicalLocation,40)}</span>` : ""}</div><footer>${esc(measurement(e))}</footer></article>`).join("") || '<p class="empty">تجهیزی برای این شرکت ثبت نشده است؛ نبود تجهیز به معنی سلامت کامل نیست.</p>';
  const issueCards=selection.issues.map((e,index)=>`<article class="issue"><header><span class="number">${(index+1).toLocaleString("fa-IR")}</span><h3>${esc(e.name)} <small>${esc(e.vendor)} · <bdi>${esc(e.host)}</bdi></small></h3><strong class="${e.status}">${reportStateLabels[e.status]}</strong></header><p><b>علت:</b> ${short(e.statusReason || e.description,240)}</p><p><b>قدم بعدی:</b> ${short(e.recommendation,290)}</p><footer>مسیر در برنامه: دارایی‌ها ← ${esc(e.name)} ← ${e.connectionState === "online" ? "نمای کلی و سنسورها" : "تنظیم اتصال و تست اتصال"}</footer></article>`).join("") || '<div class="all-clear">در بررسی‌های گزارش‌شده مورد نیازمند پیگیری ثبت نشده است. پایش و بک‌آپ دوره‌ای را ادامه دهید.</div>';
  const lines=(values: string[])=>values.length ? values.slice(0,3).map(v=>`<li>${short(v,110)}</li>`).join("") : '<li>مورد تأییدشده‌ای ثبت نشده است.</li>';
  return `<!doctype html><html lang="fa" dir="rtl"><head><meta charset="utf-8"><title>${esc(report.company.name)} - گزارش وضعیت</title><style>${reportCss(font)}</style></head><body><section class="page">
  <header class="head"><div><span class="brand">Firewall SOAR · گزارش مدیریتی</span><h1>وضعیت تجهیزات ${esc(report.company.name)}</h1><p>${report.summary.total.toLocaleString("fa-IR")} تجهیز؛ ${report.summary.limited.toLocaleString("fa-IR")} نیازمند بررسی و ${report.summary.inactive.toLocaleString("fa-IR")} کانال قطع‌شده</p></div><div class="meta"><span>شمسی: <b>${esc(report.reportDateFa)}</b></span><span>میلادی: <bdi>${esc(report.reportDateGregorian)}</bdi></span><span>ساعت تهران: <b>${esc(report.reportTime)}</b></span><span>تهیه‌کننده: ${short(report.preparedBy,55)}</span></div></header>
  <div class="summary"><div><strong>${report.summary.total.toLocaleString("fa-IR")}</strong><span>کل تجهیزات</span></div><div><strong class="active">${report.summary.active.toLocaleString("fa-IR")}</strong><span>بدون هشدار</span></div><div><strong class="limited">${report.summary.limited.toLocaleString("fa-IR")}</strong><span>نیازمند بررسی</span></div><div><strong class="inactive">${report.summary.inactive.toLocaleString("fa-IR")}</strong><span>قطع کانال مدیریتی</span></div></div>
  <section class="vendor-summary"><h2>جمع‌بندی وندورها</h2><table><thead><tr><th>وندور</th><th>تعداد</th><th>بدون هشدار</th><th>نیازمند بررسی</th><th>قطع کانال</th></tr></thead><tbody>${vendors || '<tr><td colspan="5">وندوری ثبت نشده است</td></tr>'}</tbody></table>${vendorNames.length>8 ? `<p class="omission">${vendorNames.length-8} وندور دیگر در فایل Excel فهرست شده است.</p>` : ""}</section>
  <section class="equipment"><h2>وضعیت دارایی‌ها <small>موارد نیازمند پیگیری در اولویت نمایش</small></h2>${cards}</section>
  ${report.equipment.length>selection.overview.length ? `<p class="omission">این خلاصه ${selection.overview.length.toLocaleString("fa-IR")} از ${report.equipment.length.toLocaleString("fa-IR")} تجهیز را نشان می‌دهد. برای فهرست کامل و جزئیات همهٔ تجهیزات، فرمت Excel را دریافت کنید.</p>` : ""}
  <footer class="page-footer"><bdi>${esc(report.reportNumber)}</bdi><span>۱ / ۲ · زمان هر نمونه کنار همان تجهیز آمده است</span></footer></section>
  <section class="page"><header class="followup-head"><h1>چه چیزی نیاز به پیگیری دارد؟</h1><span>${esc(report.company.name)} · ${esc(report.reportDateFa)}</span></header>
  <aside class="legend"><b>«محدود» در گزارش قبلی، یعنی نیازمند بررسی؛ نه الزاماً نداشتن مجوز.</b><p>ممکن است دستگاه آنلاین باشد اما هشدار سلامت، خطای خواندن سنسور یا دادهٔ ناکافی داشته باشد. قطع کانال مدیریتی هم لزوماً به معنی خاموش‌بودن دستگاه نیست.</p></aside>
  <section class="issues">${issueCards}</section>${report.equipment.filter(e=>e.status!=="active").length>selection.issues.length ? '<p class="omission">سایر موارد و راهکارهای کامل در شیت تجهیزات فایل Excel موجود است.</p>' : ""}
  <div class="actions"><section><h2>اقدامات انجام‌شدهٔ تأییدشده</h2><ul>${lines(report.completedActions)}</ul></section><section><h2>پیگیری‌های بعدی</h2><ul>${lines(report.futureActions)}</ul></section></div>
  ${report.additionalNotes ? `<section class="notes"><b>یادداشت مسئول:</b> ${short(report.additionalNotes,220)}</section>` : ""}
  <div class="signature">مسئول پیگیری: <b>${short(report.responsibleName,65)}</b><span>پس از اصلاح، جمع‌آوری تازه و گزارش جدید انجام شود.</span></div>
  <footer class="page-footer"><span>دادهٔ ناموجود، صفر یا سلامت قطعی محسوب نمی‌شود.</span><span>۲ / ۲</span></footer></section></body></html>`;
}
