import type { CompanyStatusEquipment, CompanyStatusReport } from "./company-status-report.types.js";

function reportCss(font: string) { return `
@font-face{font-family:IRANYekan;src:url("data:font/ttf;base64,${font}") format("truetype")}
*{box-sizing:border-box}body{margin:0;background:#e9edf2;color:#102b52;font:12px/1.45 IRANYekan,Tahoma,sans-serif;overflow-wrap:anywhere;-webkit-print-color-adjust:exact;print-color-adjust:exact}
.page{width:210mm;height:297mm;margin:0 auto 12px;background:#fff;padding:8mm;display:flex;flex-direction:column;page-break-after:always;break-after:page}.page:last-child{page-break-after:auto;break-after:auto}.page>*{flex-shrink:0}
h1,h2,h3,p{margin:0}h1{font-size:20px;line-height:1.35;color:#102653}h2{font-size:15px;margin-bottom:4px}h3{font-size:13px}small{font-size:10px;color:#536d8e}
.head{display:grid;grid-template-columns:28mm minmax(0,1fr) 54mm;gap:4mm;align-items:center;border-bottom:2px solid #17376b;padding-bottom:3mm;margin-bottom:3mm}.brand{font:bold 12px/1.25 Tahoma,sans-serif;color:#102653}.brand small{display:block;font:9px IRANYekan;color:#627d9f}.head h1{font-size:17px;text-align:center;background:#e8f1ff;border-radius:7px;padding:7px}.head p{text-align:center;font-size:11px;margin-top:3px}.meta{display:grid;gap:2px;font-size:9px;min-width:0}.meta span{display:grid;grid-template-columns:58px minmax(0,1fr);gap:3px;align-items:center}.meta b,.meta bdi{background:#fff;border:1px solid #9cb9dd;border-radius:4px;padding:2px 4px;min-height:19px;min-width:0}
.summary{display:grid;grid-template-columns:repeat(5,minmax(0,1fr));gap:5px;margin-bottom:3mm}.summary div{background:#f7faff;border:1px solid #bfd3ea;border-radius:6px;padding:4px;text-align:center}.summary strong{display:block;font-size:18px;line-height:1.25}.summary span{font-size:10px}.active{color:#217b56}.limited{color:#986320}.inactive{color:#b13a45}
.vendor-summary{border:1px solid #b8cde6;border-radius:7px;margin-bottom:3mm}.vendor-summary h2{background:#edf4fc;padding:5px 8px;margin:0}.vendor-summary table{width:100%;table-layout:fixed;border-collapse:collapse;font-size:9px;line-height:1.3}.vendor-summary th,.vendor-summary td{padding:3px 4px;border-bottom:1px solid #d8e4f1;text-align:center;overflow-wrap:anywhere}.vendor-summary th:first-child,.vendor-summary td:first-child{text-align:right;width:22%}.vendor-summary tr:last-child td{border-bottom:0}
.equipment{display:grid;gap:6px}.equipment h2{margin-bottom:0}.device{display:grid;grid-template-columns:25mm minmax(0,1fr);border:1px solid #2778c8;border-radius:8px;break-inside:avoid;background:#fff;min-width:0}.device:before{content:attr(data-vendor);grid-column:1;grid-row:1 / span 5;display:flex;align-items:center;justify-content:center;text-align:center;font-weight:800;font-size:14px;color:#2778c8;background:#eaf4ff;padding:5px}.device header,.device .identity,.device .reason,.device .facts,.device footer{grid-column:2;min-width:0}.device header{display:flex;justify-content:space-between;gap:8px;align-items:center;padding:6px 8px 0}.device h3{min-width:0}.device .identity{display:flex;flex-wrap:wrap;justify-content:space-between;gap:2px 8px;padding:0 8px;font-size:10px;color:#4e6b8e}.device .reason{font-size:11px;margin:2px 8px}.device .facts{display:flex;gap:3px 9px;flex-wrap:wrap;padding:0 8px 4px;font-size:10px}.device footer{border-top:1px solid #e1e9f2;padding:3px 8px;font-size:9px;color:#607284}.state{font-size:9px;background:#f0f4f8;border-radius:4px;padding:2px 5px;white-space:nowrap}.host{font:10px Tahoma,sans-serif;color:#173d6c}.omission{font-size:10px;background:#f2f6fa;border:1px solid #d7e2ed;border-radius:5px;padding:4px 7px;margin-top:5px}.empty{padding:12px;border:1px dashed #b6c8dc;color:#536d8e}
.device[data-category="firewall"]{border-color:#d3636b}.device[data-category="firewall"]:before{background:#fff0f1;color:#ad333e}.device[data-category="switch"]{border-color:#51ab81}.device[data-category="switch"]:before{background:#e9f8ef;color:#176e45}.device[data-category="router"]{border-color:#e7a84f}.device[data-category="router"]:before{background:#fff5e6;color:#ac660f}.device[data-category="other"]{border-color:#9083c9}.device[data-category="other"]:before{background:#f4f0ff;color:#6655a0}
.page-footer{display:flex;justify-content:space-between;gap:10px;margin-top:auto;padding-top:6px;border-top:1px solid #cbd9e8;font-size:10px;color:#627995}.followup-head{display:flex;flex-wrap:wrap;justify-content:space-between;align-items:center;gap:5px;margin-bottom:3mm}.followup-head span{font-size:10px;color:#536d8e}.legend{border:1px solid #9db6d3;background:#f3f7fc;border-right:4px solid #466b98;border-radius:6px;padding:7px 9px;margin-bottom:3mm;font-size:11px}.legend p{margin-top:2px}.issues{display:grid;gap:6px}.issue{border:1px solid #c5d6e8;border-radius:7px;padding:7px 9px;break-inside:avoid}.issue header{display:flex;gap:7px;align-items:center;margin-bottom:3px}.issue h3{flex:1;min-width:0;font-size:13px}.issue h3 small{display:block;font-size:9px}.issue p{font-size:11px;margin-bottom:3px}.issue footer{font-size:9px;color:#496b90}.number{display:grid;place-items:center;flex:0 0 20px;width:20px;height:20px;border-radius:50%;background:#eaf1f8;color:#365a80}.actions{display:grid;grid-template-columns:minmax(0,1fr) minmax(0,1fr);gap:7px;margin-top:3mm}.actions section{min-width:0;border:1px solid #c7d7e8;border-radius:6px;padding:7px}.actions h2{font-size:12px}.actions ul{padding-right:16px;margin:0;font-size:10px}.signature{display:flex;flex-wrap:wrap;gap:7px;align-items:center;margin-top:3mm;font-size:10px}.signature span{margin-right:auto;color:#647c96}
.appendix-list{display:grid;gap:5px}.appendix-device{border:1px solid #c5d6e8;border-radius:6px;padding:5px 7px;break-inside:avoid}.appendix-device header{display:flex;justify-content:space-between;align-items:center;gap:6px}.appendix-device h3{font-size:11px}.appendix-device small{font-size:8px}.appendix-device p{margin:2px 0;font-size:9px;line-height:1.35}.appendix-device footer{font-size:8px;color:#607284}.appendix-vendors table{width:100%;table-layout:fixed;border-collapse:collapse;font-size:9px}.appendix-vendors th,.appendix-vendors td{border-bottom:1px solid #d8e4f1;padding:3px;text-align:center;overflow-wrap:anywhere}
@page{size:A4;margin:0}@media print{body{background:#fff}.page{margin:0}}
`; }

const esc = (value: unknown) => String(value ?? "").replace(/[&<>"\u0027]/g, c => ({ "&": "&amp;", "<": "&lt;", ">": "&gt;", "\"": "&quot;", "\u0027": "&#39;" })[c]!);
const short = (text: string | undefined, n: number) => esc(text && text.length > n ? text.slice(0, n - 1) + "…" : text || "ثبت نشده");
export const reportStateLabels = { active: "بدون هشدار", limited: "نیازمند بررسی", inactive: "قطع کانال" } as const;
export const reportCategoryLabels = { server: "سرور", firewall: "فایروال", switch: "سوئیچ", router: "روتر", other: "سایر" } as const;
const date = (value: string | null) => value && Number.isFinite(Date.parse(value)) ? new Date(value).toLocaleString("fa-IR", { timeZone: "Asia/Tehran" }) : "زمان نامشخص";
const percent = (n: number | null) => n === null ? "—" : `${n.toLocaleString("fa-IR", { maximumFractionDigits: 1 })}٪`;
const connectionLabel = (state: CompanyStatusEquipment["connectionState"]) => state === "online" ? "برقرار" : state === "offline" ? "قطع" : state === "auth_failed" ? "ورود رد شد" : "تأیید نشده";
const source = (e: CompanyStatusEquipment, report: CompanyStatusReport) => `${e.source === "live" ? "زنده" : e.source === "snapshot" ? "ذخیره‌شده" : "موجودی"} · ${date(e.collectedAt)}${e.collectedAt && Date.parse(report.generatedAt)-Date.parse(e.collectedAt)>900000 ? " · دادهٔ قدیمی" : ""}`;
export function selectReportDetails(report: CompanyStatusReport) {
  const rank = { inactive: 0, limited: 1, active: 2 };
  const ordered = [...report.equipment].sort((a,b)=>rank[a.status]-rank[b.status]);
  return { overview: ordered.slice(0, 2), issues: ordered.filter(e=>e.status !== "active").slice(0, 2) };
}
const average = (rows: CompanyStatusEquipment[], key: "cpuPercent"|"diskPercent") => { const values=rows.map(e=>e[key]).filter((v): v is number=>v!==null); return values.length ? `${(values.reduce((a,b)=>a+b,0)/values.length).toLocaleString("fa-IR",{maximumFractionDigits:1})}٪` : "—"; };


export function renderReadableReportHtml(report: CompanyStatusReport, font: string) {
  const selection = selectReportDetails(report);
  const vendorNames = [...new Set(report.equipment.map(e=>e.vendor))];
  const stats = vendorNames.map(v=>{ const rows=report.equipment.filter(e=>e.vendor===v); return { vendor:v, rows, total:rows.length, active:rows.filter(e=>e.status==="active").length, limited:rows.filter(e=>e.status==="limited").length, inactive:rows.filter(e=>e.status==="inactive").length, online:rows.filter(e=>e.connectionState==="online").length, cpu:average(rows,"cpuPercent"), disk:average(rows,"diskPercent") }; });
  const statRow = (s: typeof stats[number]) => `<tr><th>${esc(s.vendor)}</th><td>${s.total.toLocaleString("fa-IR")}</td><td class="active">${s.active.toLocaleString("fa-IR")}</td><td class="limited">${s.limited.toLocaleString("fa-IR")}</td><td class="inactive">${s.inactive.toLocaleString("fa-IR")}</td><td>${s.online.toLocaleString("fa-IR")}</td><td>${s.cpu}</td><td>${s.disk}</td></tr>`;
  const statRows = stats.slice(0, 8).map(statRow).join("");
  const appendixVendorPages = Array.from({ length: Math.ceil(Math.max(0, stats.length - 8) / 16) }, (_, index) => stats.slice(8 + index * 16, 8 + (index + 1) * 16));
  const appendixDevicePages = Array.from({ length: Math.ceil(report.equipment.length / 7) }, (_, index) => report.equipment.slice(index * 7, (index + 1) * 7));
  const pageCount = 2 + appendixVendorPages.length + appendixDevicePages.length;
  let appendixPage = 2;
  const vendorAppendix = appendixVendorPages.map(rows => `<section class="page"><header class="followup-head"><h1>ادامهٔ خلاصهٔ وندورها</h1><span>${esc(report.company.name)}</span></header><div class="appendix-vendors"><table><thead><tr><th>وندور</th><th>کل</th><th>بدون هشدار</th><th>بررسی</th><th>قطع</th><th>آنلاین</th><th>CPU</th><th>Disk</th></tr></thead><tbody>${rows.map(statRow).join("")}</tbody></table></div><footer class="page-footer"><bdi>${esc(report.reportNumber)}</bdi><span>${(++appendixPage).toLocaleString("fa-IR")} / ${pageCount.toLocaleString("fa-IR")}</span></footer></section>`).join("");
  const deviceAppendix = appendixDevicePages.map(rows => `<section class="page"><header class="followup-head"><h1>جزئیات همهٔ تجهیزات</h1><span>${esc(report.company.name)}</span></header><div class="appendix-list">${rows.map(e => `<article class="appendix-device" data-full-device="${esc(e.id)}"><header><h3>${esc(e.name)} <small>${esc(e.vendor)} · <bdi>${esc(e.host)}</bdi></small></h3><strong class="state ${e.status}">${reportStateLabels[e.status]}</strong></header><p><b>اتصال:</b> ${connectionLabel(e.connectionState)} · <b>منبع:</b> ${source(e, report)}</p><p><b>علت:</b> ${short(e.statusReason || e.description, 160)}</p><p><b>قدم بعدی:</b> ${short(e.recommendation, 190)}</p><footer>${esc(e.model)} · CPU ${percent(e.cpuPercent)} · Disk ${percent(e.diskPercent)}</footer></article>`).join("")}</div><footer class="page-footer"><bdi>${esc(report.reportNumber)}</bdi><span>${(++appendixPage).toLocaleString("fa-IR")} / ${pageCount.toLocaleString("fa-IR")}</span></footer></section>`).join("");
  const cards = selection.overview.map(e=>`<article class="device" data-device="${esc(e.id)}" data-category="${e.category}" data-vendor="${reportCategoryLabels[e.category]}"><header><h3>${esc(e.name)}</h3><strong class="state ${e.status}">${reportStateLabels[e.status]}</strong></header><div class="identity"><span>${esc(e.vendor)} · ${short(e.model,45)}</span><bdi class="host">${esc(e.host)}</bdi></div>${e.status!=="active" ? `<p class="reason">${short(e.statusReason || e.description,100)}</p>` : ""}<div class="facts">${e.category==="server" || e.cpuPercent!==null ? `<span>CPU: <b>${percent(e.cpuPercent)}</b></span>` : ""}${e.category==="server" ? `<span>Disk: <b>${percent(e.diskPercent)}</b></span>` : ""}<span>اتصال: <b>${connectionLabel(e.connectionState)}</b></span>${e.vendorFields.slice(0,2).map(f=>`<span>${short(f.label,18)}: <bdi>${short(f.value,34)}</bdi></span>`).join("")}</div><footer>${source(e,report)}</footer></article>`).join("") || `<p class="empty">تجهیزی ثبت نشده است.</p>`;
  const issues = selection.issues.map((e,i)=>`<article class="issue"><header><span class="number">${(i+1).toLocaleString("fa-IR")}</span><h3>${esc(e.name)} <small>${esc(e.vendor)} · <bdi>${esc(e.host)}</bdi></small></h3><strong class="${e.status}">${reportStateLabels[e.status]}</strong></header><p><b>علت:</b> ${short(e.statusReason || e.description,220)}</p><p><b>قدم بعدی:</b> ${short(e.recommendation,250)}</p><footer>${e.connectionState==="online" ? "اتصال برقرار است؛ سنسور و هشدار بررسی شود." : "تنظیم اتصال و تست کانال مدیریتی بررسی شود."}</footer></article>`).join("") || `<p class="empty">مورد نیازمند بررسی ثبت نشده است.</p>`;
  const linesFor = (values: string[]) => values.length ? values.slice(0,3).map(v=>`<li>${short(v,110)}</li>`).join("") : "<li>—</li>";
  return `<!doctype html><html lang="fa" dir="rtl"><head><meta charset="utf-8"><title>${esc(report.company.name)} - گزارش وضعیت</title><style>${reportCss(font)}</style></head><body><section class="page">
  <header class="head"><div><span class="brand">IT Infrastructure<small>Report Form</small></span></div><div><h1>فرم گزارش کار تجهیزات زیرساخت IT</h1><p>وضعیت تجهیزات شرکت ${esc(report.company.name)}</p></div><div class="meta"><span>تاریخ شمسی:<b>${esc(report.reportDateFa)}</b></span><span>تاریخ میلادی:<bdi><b>${esc(report.reportDateGregorian)}</b></bdi></span><span>ساعت:<b>${esc(report.reportTime)}</b></span><span>شماره:<b>${esc(report.reportNumber)}</b></span><span>تهیه‌کننده:<b>${short(report.preparedBy,35)}</b></span></div></header>
  <div class="summary"><div><strong>${report.summary.total.toLocaleString("fa-IR")}</strong><span>کل تجهیزات</span></div><div><strong class="active">${report.summary.active.toLocaleString("fa-IR")}</strong><span>بدون هشدار</span></div><div><strong class="limited">${report.summary.limited.toLocaleString("fa-IR")}</strong><span>نیازمند بررسی</span></div><div><strong class="inactive">${report.summary.inactive.toLocaleString("fa-IR")}</strong><span>قطع کانال</span></div><div><strong>${report.summary.healthScore.toLocaleString("fa-IR")}%</strong><span>سهم بدون هشدار</span></div></div>
  <section class="vendor-summary"><h2>خلاصه آماری وندورها</h2><table><thead><tr><th>وندور</th><th>کل</th><th>بدون هشدار</th><th>بررسی</th><th>قطع</th><th>آنلاین</th><th>میانگین CPU</th><th>میانگین Disk</th></tr></thead><tbody>${statRows || `<tr><td colspan="8">—</td></tr>`}</tbody></table>${stats.length > 8 ? `<p class="omission">ادامهٔ جدول وندورها در صفحات بعدی همین PDF آمده است.</p>` : ""}</section>
  <section class="equipment"><h2>چند مورد مهم</h2>${cards}</section>${report.equipment.length>selection.overview.length ? `<p class="omission">جزئیات همهٔ ${report.equipment.length.toLocaleString("fa-IR")} تجهیز در صفحات بعدی همین PDF آمده است.</p>` : ""}
  <footer class="page-footer"><bdi>${esc(report.reportNumber)}</bdi><span>۱ / ${pageCount.toLocaleString("fa-IR")}</span></footer></section>
  <section class="page"><header class="followup-head"><h1>موارد نیازمند بررسی</h1><span>${esc(report.company.name)} · ${esc(report.reportDateFa)} · ${esc(report.reportTime)}</span></header>
  <aside class="legend"><b>«نیازمند بررسی» یعنی چه؟</b><p>تجهیز ممکن است آنلاین باشد اما هشدار، سنسور ناقص یا دادهٔ ناکافی داشته باشد؛ این برچسب به‌تنهایی نفوذ یا خرابی قطعی را ثابت نمی‌کند.</p></aside>
  <section class="issues">${issues}</section>${report.equipment.filter(e=>e.status!=="active").length>selection.issues.length ? `<p class="omission">سایر علت‌ها و راهکارها در صفحات جزئیات همین PDF آمده‌اند.</p>` : ""}
  <div class="actions"><section><h2>اقدامات انجام‌شده</h2><ul>${linesFor(report.completedActions)}</ul></section><section><h2>اقدامات بعدی</h2><ul>${linesFor(report.futureActions)}</ul></section></div>
  <div class="signature">مسئول: <b>${short(report.responsibleName,55)}</b><span>جزئیات همه تجهیزات: صفحات بعدی PDF و فایل Excel</span></div><footer class="page-footer"><span>«—» یعنی داده موجود نیست.</span><span>۲ / ${pageCount.toLocaleString("fa-IR")}</span></footer></section>${vendorAppendix}${deviceAppendix}</body></html>`;
}
