import type { FastifyInstance } from "fastify";
import { AiRiskLevel } from "@prisma/client";
import { prisma } from "../db/prisma.js";
import { proposeActionPlan } from "../services/action-plan.service.js";
import { VENDOR_TELEMETRY_PROFILES } from "../telemetry/vendor-telemetry-profiles.js";
import { serializeFinding } from "../telemetry/vendor-finding-engine.js";

export async function telemetryFindingRoutes(app: FastifyInstance) {
  app.get("/api/telemetry/profiles", async () => Object.values(VENDOR_TELEMETRY_PROFILES).map(p => ({ ...p, findingRules: p.findingRules.map(r => ({ ...r, eventPattern: r.eventPattern?.source })), suppressionRules: p.suppressionRules.map(r => ({ ...r, pattern: r.pattern.source })) })));
  app.get<{ Params: { deviceId: string }; Querystring: { status?: string } }>("/api/devices/:deviceId/findings", async request => (await prisma.finding.findMany({ where: { deviceId: request.params.deviceId, ...(request.query.status ? { status: request.query.status } : {}) }, orderBy: [{ severity: "desc" }, { confidence: "desc" }, { lastSeen: "desc" }] })).map(x => serializeFinding(x as unknown as Record<string, unknown>)));
  app.patch<{ Params: { id: string }; Body: { status: "active" | "acknowledged" | "resolved" } }>("/api/findings/:id", async (request, reply) => { if (!["active", "acknowledged", "resolved"].includes(request.body.status)) return reply.code(400).send({ error: "Invalid finding status" }); return serializeFinding(await prisma.finding.update({ where: { id: request.params.id }, data: { status: request.body.status } }) as unknown as Record<string, unknown>); });
  app.post<{ Params: { id: string }; Body: { recommendedIntent?: string } }>("/api/findings/:id/action-plan", async (request, reply) => { const finding = await prisma.finding.findUnique({ where: { id: request.params.id } }); if (!finding) return reply.code(404).send({ error: "Finding not found" }); const actions = Array.isArray(finding.recommendedActions) ? finding.recommendedActions as Array<Record<string, unknown>> : []; const recommendedIntent = request.body?.recommendedIntent ?? String(actions[0]?.intent ?? "generic_security_action"); const plan = await proposeActionPlan({ source: "system", requestedBy: `finding:${finding.id}`, deviceId: finding.deviceId, vendor: finding.vendor, actionType: "custom_vendor_action", riskLevel: finding.severity as AiRiskLevel, parametersJson: { findingId: finding.id, vendor: finding.vendor, deviceId: finding.deviceId, title: finding.title, evidence: finding.evidenceJson, recommendedIntent, requestedOperation: recommendedIntent, operationCategory: "finding_remediation", executionSupport: "manual_or_not_implemented", requiresExplicitReview: true } }); return reply.code(201).send({ findingId: finding.id, actionPlan: plan }); });
}
