import { useEffect, useMemo, useState } from "react";
import { Building2, CheckCircle2, Download, FileCode2, FileSpreadsheet, FileText, LoaderCircle, PencilLine, RefreshCw, ServerCog } from "lucide-react";
import { listCompanies, type Company } from "@/lib/companies";
import { createCompanyStatusReport, downloadCompanyStatusReport, type CompanyStatusEquipment, type CompanyStatusReport, type ReportFormat } from "@/lib/reports";
import "./ReportsPage.css";

const stateLabel = { active: "فعال", limited: "محدود", inactive: "غیرفعال" } as const;
const categoryLabel = { server: "سرور", firewall: "فایروال", switch: "سوئیچ", router: "روتر", other: "سایر" } as const;
const formatOptions: Array<{ id: ReportFormat; label: string; Icon: typeof FileText }> = [{ id: "pdf", label: "PDF", Icon: FileText }, { id: "xlsx", label: "Excel", Icon: FileSpreadsheet }, { id: "html", label: "HTML", Icon: FileCode2 }];

export default function ReportsPage() {
  const [companies, setCompanies] = useState<Company[]>([]), [companyId, setCompanyId] = useState(""), [report, setReport] = useState<CompanyStatusReport | null>(null), [format, setFormat] = useState<ReportFormat>("pdf");
  const [loading, setLoading] = useState(true), [generating, setGenerating] = useState(false), [exporting, setExporting] = useState(false), [error, setError] = useState("");
  useEffect(() => { void listCompanies().then((items) => { setCompanies(items); setCompanyId(items[0]?.id ?? ""); }).catch((reason) => setError(reason instanceof Error ? reason.message : "دریافت شرکت‌ها ناموفق بود")).finally(() => setLoading(false)); }, []);
  const vendors = useMemo(() => report ? [...new Set(report.equipment.map((item) => item.vendor))] : [], [report]);
  const updateReport = <K extends keyof CompanyStatusReport>(key: K, value: CompanyStatusReport[K]) => setReport((current) => current ? { ...current, [key]: value } : current);
  const updateEquipment = (id: string, patch: Partial<CompanyStatusEquipment>) => setReport((current) => current ? { ...current, equipment: current.equipment.map((item) => item.id === id ? { ...item, ...patch } : item) } : current);
  const generate = async () => { if (!companyId) return; setGenerating(true); setError(""); try { setReport(await createCompanyStatusReport(companyId)); } catch (reason) { setError(reason instanceof Error ? reason.message : "ساخت گزارش ناموفق بود"); } finally { setGenerating(false); } };
  const download = async () => { if (!report) return; setExporting(true); setError(""); try { await downloadCompanyStatusReport(report, format); } catch (reason) { setError(reason instanceof Error ? reason.message : "دریافت فایل ناموفق بود"); } finally { setExporting(false); } };

  return <section className="reports-page" dir="rtl">
    <header className="reports-hero"><div><span>گزارش‌گیری مدیریتی</span><h1>وضعیت تجهیزات شرکت</h1><p>آخرین دادهٔ واقعی تجهیزات را ببینید، در صورت نیاز ویرایش کنید و در قالب دلخواه تحویل بگیرید.</p></div><div className="reports-hero__mark"><FileText/><small>حداکثر دو صفحه</small></div></header>
    <section className="reports-controls">
      <label><span><Building2/> شرکت</span><select value={companyId} onChange={(event) => { setCompanyId(event.target.value); setReport(null); }} disabled={loading}>{companies.map((company) => <option value={company.id} key={company.id}>{company.name} · {company.code}</option>)}</select></label>
      <button className="reports-generate" type="button" disabled={!companyId || generating} onClick={() => void generate()}>{generating ? <LoaderCircle className="spin"/> : <RefreshCw/>}{generating ? "در حال جمع‌آوری دادهٔ زنده…" : report ? "ساخت گزارش جدید" : "گزارش وضعیت"}</button>
      <div className="reports-formats" aria-label="فرمت خروجی">{formatOptions.map(({ id, label, Icon }) => <button type="button" key={id} className={format === id ? "active" : ""} onClick={() => setFormat(id)}><Icon/>{label}</button>)}</div>
      <button className="reports-download" type="button" disabled={!report || exporting} onClick={() => void download()}>{exporting ? <LoaderCircle className="spin"/> : <Download/>}{exporting ? "در حال ساخت فایل…" : `دریافت ${format.toUpperCase()}`}</button>
    </section>
    {error && <p className="reports-error">{error}</p>}
    {!report && !loading ? <div className="reports-empty"><ServerCog/><h2>شرکت را انتخاب کنید</h2><p>با زدن «گزارش وضعیت»، بک‌اند مستقیماً آخرین وضعیت وندورها را جمع‌آوری می‌کند.</p></div> : null}
    {report ? <div className="report-editor">
      <div className="report-editor__hint"><PencilLine/><span>همهٔ کادرهای سفید قابل ویرایش‌اند. محل فیزیکی عمداً خالی گذاشته شده است.</span><b><CheckCircle2/> آخرین جمع‌آوری: {report.reportDateFa}، ساعت {report.reportTime} تهران</b></div>
      <article className="report-paper">
        <header className="report-paper__head"><div className="report-paper__brand"><FileText/> IT Infrastructure<small>Report Form</small></div><div className="report-paper__title"><h2>فرم گزارش کار تجهیزات زیرساخت IT</h2><p>وضعیت تجهیزات شرکت {report.company.name}</p></div><div className="report-paper__meta"><label>تاریخ شمسی<input value={report.reportDateFa} onChange={(event) => updateReport("reportDateFa", event.target.value)}/></label><label>تاریخ میلادی<input dir="ltr" value={report.reportDateGregorian} onChange={(event) => updateReport("reportDateGregorian", event.target.value)}/></label><label>ساعت تهران<input value={report.reportTime} onChange={(event) => updateReport("reportTime", event.target.value)}/></label><label>شماره گزارش<input value={report.reportNumber} onChange={(event) => updateReport("reportNumber", event.target.value)}/></label><label>تهیه‌کننده<input value={report.preparedBy} onChange={(event) => updateReport("preparedBy", event.target.value)}/></label></div></header>
        <div className="report-paper__summary"><div className="score"><small>امتیاز سلامت</small><strong>{report.summary.healthScore.toLocaleString("fa-IR")}%</strong></div><div><small>کل</small><strong>{report.summary.total.toLocaleString("fa-IR")}</strong></div><div><small>فعال</small><strong>{report.summary.active.toLocaleString("fa-IR")}</strong></div><div><small>محدود</small><strong>{report.summary.limited.toLocaleString("fa-IR")}</strong></div><div><small>غیرفعال</small><strong>{report.summary.inactive.toLocaleString("fa-IR")}</strong></div></div>
        <div className="report-vendors">{vendors.map((vendor, index) => { const rows = report.equipment.filter((item) => item.vendor === vendor); return <section className={`report-vendor tone-${index % 6}`} key={vendor}><header><ServerCog/><strong>{vendor}</strong><small>{rows.length.toLocaleString("fa-IR")} تجهیز</small></header><div>{rows.map((item) => <EquipmentEditor key={item.id} item={item} onChange={(patch) => updateEquipment(item.id, patch)}/>)}</div></section>; })}</div>
        <div className="report-paper__actions"><label><span>اقدامات انجام‌شده</span><textarea value={report.completedActions.join("\n")} onChange={(event) => updateReport("completedActions", event.target.value.split("\n"))}/></label><label><span>برنامه‌ها و اقدامات آتی</span><textarea value={report.futureActions.join("\n")} onChange={(event) => updateReport("futureActions", event.target.value.split("\n"))}/></label></div>
        <label className="report-paper__notes"><span>توضیحات اضافی</span><textarea value={report.additionalNotes} onChange={(event) => updateReport("additionalNotes", event.target.value)}/></label>
        <label className="report-paper__responsible"><span>نام مسئول</span><input value={report.responsibleName} onChange={(event) => updateReport("responsibleName", event.target.value)}/></label>
      </article>
    </div> : null}
  </section>;
}

function EquipmentEditor({ item, onChange }: { item: CompanyStatusEquipment; onChange: (patch: Partial<CompanyStatusEquipment>) => void }) {
  return <article className="equipment-editor"><div className="equipment-editor__grid"><label>نام تجهیز<input value={item.name} onChange={(event) => onChange({ name: event.target.value })}/></label><label>IP Address<input dir="ltr" value={item.host} onChange={(event) => onChange({ host: event.target.value })}/></label><label>مدل / پلتفرم<input value={item.model} onChange={(event) => onChange({ model: event.target.value })}/></label><label>نوع<input value={categoryLabel[item.category]} readOnly/></label><label>محل فیزیکی<input value={item.physicalLocation} placeholder="توسط کاربر تکمیل شود" onChange={(event) => onChange({ physicalLocation: event.target.value })}/></label><label>وضعیت<select value={item.status} onChange={(event) => onChange({ status: event.target.value as CompanyStatusEquipment["status"] })}><option value="active">فعال</option><option value="limited">محدود</option><option value="inactive">غیرفعال</option></select></label></div>{item.category === "server" ? <div className="equipment-editor__health"><span>CPU <b>{item.cpuPercent ?? "داده موجود نیست"}{item.cpuPercent === null ? "" : "%"}</b></span><span>Disk <b>{item.diskPercent ?? "داده موجود نیست"}{item.diskPercent === null ? "" : "%"}</b></span></div> : null}<div className="equipment-editor__facts">{item.vendorFields.map((field) => <span key={`${field.label}-${field.value}`}><b>{field.label}</b>{field.value}</span>)}</div><label className="equipment-editor__description">توضیحات<input value={item.description} onChange={(event) => onChange({ description: event.target.value })}/></label><footer><span className={item.status}>{stateLabel[item.status]}</span><span>{item.source === "live" ? "داده زنده" : item.source === "snapshot" ? "آخرین Snapshot" : "موجودی ثبت‌شده"}</span><time>{item.collectedAt ? new Date(item.collectedAt).toLocaleString("fa-IR", { timeZone: "Asia/Tehran" }) : "داده زمانی موجود نیست"}</time></footer></article>;
}
