import { useEffect, useMemo, useRef, useState } from "react";
import { Activity, Bot, Check, Pause, Play, RefreshCw, Square, Trash2, Wrench } from "lucide-react";
import { proposeAction } from "@/lib/actions";
import { publishActionPlanCreated } from "@/lib/actionPlanHandoff";
import { sendAiMessage } from "@/lib/ai";
import { listDevices, type Device } from "@/lib/devices";
import { collectLinuxSnapshot, latestLinuxSnapshot, linuxStreamStatus, linuxTelemetryOptions, startLinuxStream, stopLinuxStream, subscribeLinuxStream, type LinuxLiveEvent, type LinuxSnapshot, type LinuxTelemetryOptions } from "@/lib/linuxTelemetry";
import { buildFixActionProposal, buildLiveFindings, compactLiveFindingSummary, sourcesForPreset, type LiveFinding, type SourcePreset } from "@/lib/linuxTelemetryFindings";

const allSources = ["auth", "system", "kernel", "firewall", "nginx", "docker"];
const presetLabels: Record<SourcePreset, string> = { essential: "Essential Security", web: "Web Server", docker: "Docker Host", full: "Full Observation" };
const severityClass: Record<string, string> = { info: "border-cyan-900 text-cyan-200", low: "border-blue-900 text-blue-200", medium: "border-yellow-900 text-yellow-200", high: "border-red-900 text-red-200", critical: "border-red-700 bg-red-950/40 text-red-100" };

export function isLinuxTelemetryDevice(device: Device) {
  const vendor = String(device.vendor ?? "").toLowerCase(); const type = String(device.type ?? "").toLowerCase(); const capabilities = JSON.stringify(device.capabilities ?? {}).toLowerCase();
  return (vendor === "linux" || vendor.includes("ubuntu") || vendor.includes("linux") || type === "linux" || type === "linux_edge" || capabilities.includes("linux")) && (device.protocol === "ssh" || capabilities.includes("ssh"));
}

export function smartMonitoringSources(options: LinuxTelemetryOptions | null, snapshot: LinuxSnapshot | null) {
  const available = options?.logSourcesAvailable ?? allSources;
  const selected = new Set(sourcesForPreset("essential", available));
  if (snapshot?.containers?.dockerDetected) selected.add("docker");
  const services = snapshot?.services?.importantServices ?? {};
  if ([services.nginx, services.apache2].some((value) => value === "detected")) selected.add("nginx");
  return Array.from(selected).filter((source) => available.includes(source));
}

export default function LinuxTelemetryPanel() {
  const [devices, setDevices] = useState<Device[]>([]); const [deviceId, setDeviceId] = useState(""); const [snapshot, setSnapshot] = useState<LinuxSnapshot | null>(null); const [options, setOptions] = useState<LinuxTelemetryOptions | null>(null);
  const [selectedSources, setSelectedSources] = useState<string[]>(["auth", "system", "firewall", "kernel"]); const [streamId, setStreamId] = useState(""); const [events, setEvents] = useState<LinuxLiveEvent[]>([]); const [warnings, setWarnings] = useState<string[]>([]);
  const [paused, setPaused] = useState(false); const [pausedEvents, setPausedEvents] = useState<LinuxLiveEvent[]>([]); const [suspiciousOnly, setSuspiciousOnly] = useState(false); const [sourceFilter, setSourceFilter] = useState("all"); const [severityFilter, setSeverityFilter] = useState("all");
  const [acknowledged, setAcknowledged] = useState<Set<string>>(new Set()); const [createdActions, setCreatedActions] = useState<Record<string, string>>({}); const [working, setWorking] = useState(""); const [message, setMessage] = useState(""); const [aiMessage, setAiMessage] = useState(""); const [subscriptionNonce, setSubscriptionNonce] = useState(0);
  const currentDeviceRef = useRef(deviceId); currentDeviceRef.current = deviceId;

  useEffect(() => { listDevices().then((items) => { const linux = items.filter(isLinuxTelemetryDevice).sort((a, b) => Number(b.status === "online") - Number(a.status === "online")); const remembered = sessionStorage.getItem("linuxTelemetryDeviceId"); setDevices(linux); setDeviceId((current) => current || (remembered && linux.some((item) => item.id === remembered) ? remembered : linux[0]?.id ?? "")); }).catch((error) => setMessage(error.message)); }, []);
  useEffect(() => { if (!deviceId) return; sessionStorage.setItem("linuxTelemetryDeviceId", deviceId); setSnapshot(null); setEvents([]); setWarnings([]); Promise.allSettled([linuxTelemetryOptions(deviceId), latestLinuxSnapshot(deviceId), linuxStreamStatus(deviceId)]).then(([optionResult, snapshotResult, statusResult]) => { if (currentDeviceRef.current !== deviceId) return; if (optionResult.status === "fulfilled") setOptions(optionResult.value); if (snapshotResult.status === "fulfilled") setSnapshot(snapshotResult.value.snapshot); if (statusResult.status === "fulfilled" && statusResult.value.status === "running" && statusResult.value.streamId) { setStreamId(statusResult.value.streamId); setSelectedSources(statusResult.value.sources); setWarnings(statusResult.value.warnings); } }); }, [deviceId]);
  useEffect(() => { if (!deviceId || !streamId) return; return subscribeLinuxStream(deviceId, streamId, (event) => setEvents((current) => [...current.slice(-499), event]), () => setMessage("Live connection is reconnecting; the server-side stream remains active."), (warning) => setWarnings((current) => Array.from(new Set([...current, warning])).slice(-20))); }, [deviceId, streamId, subscriptionNonce]);

  const findings = useMemo(() => buildLiveFindings(events, snapshot), [events, snapshot]);
  const eventView = paused ? pausedEvents : events;
  const visibleEvents = useMemo(() => eventView.filter((event) => (!suspiciousOnly || event.suspicious) && (sourceFilter === "all" || event.source === sourceFilter) && (severityFilter === "all" || event.severity === severityFilter)), [eventView, suspiciousOnly, sourceFilter, severityFilter]);
  const selectedDevice = devices.find((device) => device.id === deviceId); const connectionHost = options?.connection.host ?? snapshot?.connection.host ?? selectedDevice?.host ?? "unknown"; const connectionPort = options?.connectionPort ?? snapshot?.connection.connectionPort ?? selectedDevice?.managementPort ?? 22;

  const refreshOptions = async () => setOptions(await linuxTelemetryOptions(deviceId));
  const collectBaseline = async () => { const result = await collectLinuxSnapshot(deviceId); setSnapshot(result.snapshot); await refreshOptions(); return result.snapshot; };
  const applyPreset = (preset: SourcePreset) => setSelectedSources(sourcesForPreset(preset, options?.logSourcesAvailable ?? allSources));
  const startMonitoring = async () => {
    setWorking("monitor"); setMessage(""); setWarnings([]);
    const smartSources = smartMonitoringSources(options, snapshot); setSelectedSources(smartSources);
    try {
      const result = await startLinuxStream(deviceId, smartSources); setStreamId(result.streamId); setWarnings(result.warnings ?? []); setMessage("Live security monitoring started.");
      const last = options?.lastSnapshotAt ? new Date(options.lastSnapshotAt).getTime() : 0;
      if (!snapshot || Date.now() - last > 15 * 60_000) void collectBaseline().catch((error) => setWarnings((current) => [...current, `Baseline: ${error instanceof Error ? error.message : "failed"}`]));
    } catch (error) { setMessage(error instanceof Error ? error.message : "Monitoring failed"); } finally { setWorking(""); }
  };
  const startManual = async () => { setWorking("stream"); try { const result = await startLinuxStream(deviceId, selectedSources); setStreamId(result.streamId); setWarnings(result.warnings ?? []); setMessage("Selected streams started."); } catch (error) { setMessage(error instanceof Error ? error.message : "Stream failed"); } finally { setWorking(""); } };
  const stopMonitoring = async () => { if (!streamId) return; setWorking("stop"); try { await stopLinuxStream(deviceId, streamId); setStreamId(""); setMessage("Monitoring stopped. Events and findings remain visible."); } finally { setWorking(""); } };
  const togglePause = () => { if (!paused) setPausedEvents(events); setPaused(!paused); };
  const acknowledge = (id: string) => setAcknowledged((current) => new Set(current).add(id));
  const createFixAction = async (finding: LiveFinding) => { setWorking(`action:${finding.id}`); try { const plan = await proposeAction(buildFixActionProposal(finding, deviceId)); setCreatedActions((current) => ({ ...current, [finding.id]: plan.id })); publishActionPlanCreated(plan.id); setMessage("Fix ActionPlan created for review. Nothing was executed."); } catch (error) { setMessage(error instanceof Error ? error.message : "ActionPlan creation failed"); } finally { setWorking(""); } };
  const analyzeLive = async () => { setWorking("ai"); try { const compact = compactLiveFindingSummary(deviceId, findings, snapshot); const response = await sendAiMessage(null, `Analyze this compact Linux live telemetry summary. Explain priorities only; do not claim execution.\n${JSON.stringify(compact)}`); setAiMessage(response.assistantMessage?.content ?? response.structured?.assistantMessage ?? "Analysis completed."); } catch (error) { setAiMessage(error instanceof Error ? error.message : "AI analysis failed"); } finally { setWorking(""); } };

  if (!deviceId) return <section className="text-left"><h2 className="text-lg font-semibold text-zinc-100">Linux Telemetry</h2><p className="mt-4 border-y border-zinc-800 py-8 text-center text-sm text-zinc-500">No Linux SSH device found. Add a Linux device with SSH credentials first.</p></section>;
  return <section className="text-left">
    <div className="mb-4 flex items-center gap-2"><Activity className="h-5 w-5 text-cyan-300"/><div><h2 className="text-lg font-semibold text-zinc-100">Linux Telemetry</h2><p className="text-xs text-zinc-500">Real-time, read-only security monitoring. Fix actions are proposals only.</p></div></div>
    <div className="grid gap-5 xl:grid-cols-[minmax(260px,0.85fr)_minmax(340px,1.15fr)_minmax(420px,1.5fr)]">
      <section className="border-t border-zinc-800 pt-3"><h3 className="text-sm font-semibold text-zinc-200">Monitoring Controls</h3>
        <label className="mt-3 block text-xs text-zinc-500">Linux device<select value={deviceId} onChange={(event) => { setStreamId(""); setDeviceId(event.target.value); }} className="mt-1 h-9 w-full rounded border border-zinc-700 bg-zinc-950 px-2 text-sm text-zinc-100">{devices.map((device) => <option key={device.id} value={device.id}>{device.name} ({device.host})</option>)}</select></label>
        <dl className="mt-3 grid grid-cols-2 gap-x-3 gap-y-2 text-xs"><Status label="Connection" value={`${options?.connectionStatus ?? selectedDevice?.status ?? "unknown"}`}/><Status label="Endpoint" value={`${connectionHost}:${connectionPort}`}/><Status label="Detected SSH service" value={String(options?.detectedSshServicePort ?? snapshot?.ssh.detectedSshServicePort ?? "not collected")}/><Status label="Privilege" value={snapshot?.privilegeLevel ?? options?.privilegeLevel ?? "unknown"}/><Status label="Sudo" value={String(snapshot?.sudoAvailable ?? options?.sudoAvailable ?? "unknown")}/><Status label="Monitoring" value={streamId ? "live" : "stopped"}/><Status label="Sources" value={String(selectedSources.length)}/></dl>
        {!streamId ? <button type="button" onClick={startMonitoring} disabled={Boolean(working)} className="mt-4 inline-flex h-10 w-full items-center justify-center gap-2 rounded border border-green-800 bg-green-950/30 px-3 text-sm font-semibold text-green-100 disabled:opacity-50"><Play className="h-4 w-4"/>Start Live Security Monitoring</button> : <button type="button" onClick={stopMonitoring} disabled={Boolean(working)} className="mt-4 inline-flex h-10 w-full items-center justify-center gap-2 rounded border border-red-900 bg-red-950/20 px-3 text-sm font-semibold text-red-100 disabled:opacity-50"><Square className="h-4 w-4"/>Stop Monitoring</button>}
        <div className="mt-3 flex gap-2"><IconButton title="Reconnect viewer" onClick={() => setSubscriptionNonce((value) => value + 1)} icon={RefreshCw}/><IconButton title={paused ? "Resume display" : "Pause display"} onClick={togglePause} icon={paused ? Play : Pause}/><IconButton title="Clear local events" onClick={() => { setEvents([]); setPausedEvents([]); }} icon={Trash2}/></div>
        <h4 className="mt-5 text-xs font-semibold uppercase text-zinc-500">Source presets</h4><div className="mt-2 grid gap-2">{(Object.keys(presetLabels) as SourcePreset[]).map((preset) => <button key={preset} type="button" disabled={Boolean(streamId)} onClick={() => applyPreset(preset)} className="h-8 rounded border border-zinc-800 px-2 text-left text-xs text-zinc-300 disabled:opacity-40">{presetLabels[preset]}</button>)}</div>
        <details className="mt-3 border-t border-zinc-800 pt-2"><summary className="cursor-pointer text-xs font-medium text-zinc-400">Advanced sources</summary><div className="mt-2 grid grid-cols-2 gap-2">{(options?.logSourcesAvailable ?? allSources).map((source) => <label key={source} className="flex items-center gap-1.5 text-xs text-zinc-400"><input type="checkbox" disabled={Boolean(streamId)} checked={selectedSources.includes(source)} onChange={() => setSelectedSources((current) => current.includes(source) ? current.filter((item) => item !== source) : [...current, source])}/>{source}</label>)}</div><button type="button" disabled={Boolean(streamId) || !selectedSources.length || Boolean(working)} onClick={startManual} className="mt-3 h-8 w-full rounded border border-cyan-900 text-xs font-semibold text-cyan-100 disabled:opacity-40">Start selected sources</button></details>
        {warnings.length > 0 && <div className="mt-4 border-t border-yellow-900/40 pt-2">{warnings.map((warning, index) => <p key={`${warning}-${index}`} className="mt-1 text-xs text-yellow-200">{warning}</p>)}</div>}
      </section>
      <section className="border-t border-zinc-800 pt-3"><div className="flex items-center justify-between"><h3 className="text-sm font-semibold text-zinc-200">Live Findings <span className="text-zinc-500">({findings.length})</span></h3><button type="button" onClick={analyzeLive} disabled={!findings.length || working === "ai"} className="inline-flex h-8 items-center gap-1.5 rounded border border-cyan-900 px-2 text-xs text-cyan-100 disabled:opacity-40"><Bot className="h-3.5 w-3.5"/>Analyze</button></div>
        <label className="mt-3 flex items-center gap-2 text-xs text-zinc-400"><input type="checkbox" checked={suspiciousOnly} onChange={(event) => setSuspiciousOnly(event.target.checked)}/>Suspicious events only</label>
        <div className="mt-3 max-h-[620px] divide-y divide-zinc-800 overflow-auto border-y border-zinc-800">{findings.length ? findings.map((finding) => { const status = createdActions[finding.id] ? "action_created" : acknowledged.has(finding.id) ? "acknowledged" : "live"; return <article key={finding.id} className="py-3"><div className="flex flex-wrap items-center gap-2"><span className={`rounded border px-2 py-0.5 text-[11px] ${severityClass[finding.severity]}`}>{finding.severity}</span><span className="text-[11px] text-zinc-500">{status}</span><span className="text-[11px] text-zinc-600">count {finding.count}</span></div><h4 className="mt-2 text-sm font-medium text-zinc-100">{finding.title}</h4><p className="mt-1 text-xs text-zinc-400">{finding.evidence.join(" · ")}</p><p className="mt-1 text-[11px] text-zinc-500">{[finding.sourceIp && `IP ${finding.sourceIp}`, finding.port && `port ${finding.port}`, finding.username && `user ${finding.username}`].filter(Boolean).join(" · ") || finding.source} · first {new Date(finding.firstSeen).toLocaleTimeString()} · last {new Date(finding.lastSeen).toLocaleTimeString()}</p><p className="mt-2 text-xs text-cyan-100/80">{finding.recommendedFix}</p><div className="mt-2 flex gap-2"><button type="button" onClick={() => acknowledge(finding.id)} disabled={status !== "live"} className="inline-flex h-7 items-center gap-1 rounded border border-zinc-700 px-2 text-[11px] text-zinc-300 disabled:opacity-40"><Check className="h-3 w-3"/>Acknowledge</button>{finding.actionable && <button type="button" onClick={() => createFixAction(finding)} disabled={Boolean(createdActions[finding.id]) || working === `action:${finding.id}`} className="inline-flex h-7 items-center gap-1 rounded border border-blue-900 px-2 text-[11px] text-blue-200 disabled:opacity-40"><Wrench className="h-3 w-3"/>Create Fix Action</button>}</div></article>; }) : <p className="py-8 text-center text-sm text-zinc-600">Findings will appear here while monitoring is live.</p>}</div>
        {aiMessage && <div className="mt-3 border-l-2 border-cyan-800 pl-3 text-xs leading-5 text-zinc-300">{aiMessage}</div>}
      </section>
      <section className="border-t border-zinc-800 pt-3"><h3 className="text-sm font-semibold text-zinc-200">Live Events <span className="text-zinc-500">({visibleEvents.length})</span></h3><div className="mt-3 flex flex-wrap gap-2"><select value={sourceFilter} onChange={(event) => setSourceFilter(event.target.value)} className="h-8 rounded border border-zinc-700 bg-zinc-950 px-2 text-xs text-zinc-300"><option value="all">All sources</option>{allSources.map((source) => <option key={source}>{source}</option>)}</select><select value={severityFilter} onChange={(event) => setSeverityFilter(event.target.value)} className="h-8 rounded border border-zinc-700 bg-zinc-950 px-2 text-xs text-zinc-300"><option value="all">All severity</option>{["info", "low", "medium", "high", "critical"].map((severity) => <option key={severity}>{severity}</option>)}</select>{paused && <span className="self-center text-xs text-yellow-200">Display paused; collection continues.</span>}</div>
        <div className="mt-3 max-h-[660px] overflow-auto border-y border-zinc-800 font-mono text-xs">{visibleEvents.length ? visibleEvents.map((event, index) => <div key={`${event.timestamp}-${index}`} className={`border-b border-zinc-900 px-2 py-2 ${event.suspicious ? "bg-red-950/10" : ""}`}><div className="flex flex-wrap gap-2"><span className="text-zinc-600">{new Date(event.timestamp).toLocaleTimeString()}</span><span className="text-cyan-300">{event.source}</span><span className={severityClass[event.severity]?.split(" ").at(-1)}>{event.severity}</span>{event.suspicious && <span className="text-red-300">suspicious</span>}</div><p className="mt-1 text-zinc-300">{event.summary}</p><details className="mt-1"><summary className="cursor-pointer text-zinc-600">evidence</summary><pre className="mt-1 whitespace-pre-wrap break-words text-zinc-500">{event.raw}</pre></details></div>) : <p className="px-3 py-8 text-center text-zinc-600">Start monitoring to receive live events.</p>}</div>
      </section>
    </div>
    {message && <p className="mt-4 text-xs text-yellow-200" role="status">{message}</p>}
  </section>;
}

function Status({ label, value }: { label: string; value: string }) { return <div><dt className="text-zinc-600">{label}</dt><dd className="mt-0.5 truncate text-zinc-300">{value}</dd></div>; }
function IconButton({ title, onClick, icon: Icon }: { title: string; onClick: () => void; icon: typeof Activity }) { return <button type="button" title={title} onClick={onClick} className="rounded border border-zinc-700 p-2 text-zinc-300"><Icon className="h-4 w-4"/></button>; }
