[CmdletBinding()]
param()

$ErrorActionPreference = "Stop"
$root = (Resolve-Path (Join-Path $PSScriptRoot "..")).Path
$outputPath = Join-Path $root "docs\PROJECT_SNAPSHOT.md"

function Read-PackageInfo([string]$path) {
    if (-not (Test-Path -LiteralPath $path)) { return @{ Name = "missing"; Version = "missing" } }
    $package = Get-Content -Raw -LiteralPath $path | ConvertFrom-Json
    return @{ Name = [string]$package.name; Version = [string]$package.version }
}

function Relative-Directories([string]$path) {
    if (-not (Test-Path -LiteralPath $path)) { return @() }
    return @(Get-ChildItem -LiteralPath $path -Directory | Sort-Object Name | ForEach-Object { $_.Name })
}

Push-Location $root
try {
    $timestamp = Get-Date -Format "yyyy-MM-dd HH:mm:ss zzz"
    $branch = (git branch --show-current).Trim()
    $latestCommit = (git log -1 --pretty=format:"%h %ad %s" --date=iso-strict).Trim()
    $status = @(git status --short)
    $rootPackage = Read-PackageInfo (Join-Path $root "package.json")
    $backendPackage = Read-PackageInfo (Join-Path $root "backend\package.json")
    $backendDirectories = Relative-Directories (Join-Path $root "backend\src")
    $frontendDirectories = Relative-Directories (Join-Path $root "src")
    $routeFiles = @(Get-ChildItem -LiteralPath (Join-Path $root "backend\src\routes") -Filter "*.ts" -File | Sort-Object Name | ForEach-Object { "backend/src/routes/$($_.Name)" })
    $modelNames = @(Select-String -LiteralPath (Join-Path $root "backend\prisma\schema.prisma") -Pattern '^model\s+([A-Za-z0-9_]+)' | ForEach-Object { $_.Matches[0].Groups[1].Value })

    $catalogPath = Join-Path $root "backend\src\commands\catalog\index.ts"
    $catalogRows = @(Select-String -LiteralPath $catalogPath -Pattern '^\s*item\("([^"]+)".*\b(implemented|manual|planned)\(' | ForEach-Object {
        [PSCustomObject]@{ Vendor = $_.Matches[0].Groups[1].Value; State = $_.Matches[0].Groups[2].Value }
    })
    $catalogSummary = @($catalogRows | Group-Object Vendor | Sort-Object Name | ForEach-Object {
        $implemented = @($_.Group | Where-Object State -eq "implemented").Count
        $manualOnly = @($_.Group | Where-Object State -eq "manual").Count
        $planned = @($_.Group | Where-Object State -eq "planned").Count
        "- $($_.Name): total=$($_.Count), implemented=$implemented, manualOnly=$manualOnly, planned=$planned"
    })

    $sensitiveEnvPattern = '(^|/)(\.env|[^/]+\.env)$|(^|/)\.env\.(local|production|development)$'
    $trackedEnv = @(git ls-files | Where-Object { $_ -match $sensitiveEnvPattern })
    $lines = @(
        "# Project Snapshot",
        "",
        "> Generated by ``scripts/project-snapshot.ps1``. Do not edit manually.",
        "",
        "- Timestamp: $timestamp",
        "- Git branch: ``$branch``",
        "- Latest commit: ``$latestCommit``",
        "- Root package: ``$($rootPackage.Name)@$($rootPackage.Version)``",
        "- Backend package: ``$($backendPackage.Name)@$($backendPackage.Version)``",
        "",
        "## Git Status",
        ""
    )
    if ($status.Count -eq 0) { $lines += "Working tree clean." } else { $lines += @("``````text") + $status + @("``````") }
    $backendDirectoryText = ($backendDirectories | ForEach-Object { "``backend/src/$_``" }) -join ", "
    $frontendDirectoryText = ($frontendDirectories | ForEach-Object { "``src/$_``" }) -join ", "
    $lines += @("", "## Main Directories", "", "- Backend: $backendDirectoryText", "- Frontend: $frontendDirectoryText", "", "## API Route Files", "")
    $lines += $routeFiles | ForEach-Object { "- ``$_``" }
    $lines += @("", "## Prisma Models", "", ($modelNames -join ", "), "", "## Command Catalog by Vendor", "")
    $lines += $catalogSummary
    $lines += @("", "## Validation Commands", "", "- Backend: ``cd backend; npm run build; npm test``", "- Catalog: ``cd backend; npm run validate:command-catalog``", "- Frontend: ``pnpm build``", "- Memory: ``pnpm docs:check``", "", "## Tracked .env Warning", "")
    if ($trackedEnv.Count -eq 0) { $lines += "No tracked .env files detected." } else { $lines += "WARNING: tracked environment file paths detected: " + ($trackedEnv -join ", ") }

    Set-Content -LiteralPath $outputPath -Value $lines -Encoding UTF8
    Write-Output "Wrote docs/PROJECT_SNAPSHOT.md"
} finally {
    Pop-Location
}
