export const FINDING_CATEGORIES = ["auth", "privilege", "config_change", "management_exposure", "firewall_vpn", "deny_drop_burst", "malware_threat", "log_tamper", "service_health", "web_app", "container_runtime", "cloud_control_plane", "posture"] as const;
export type FindingCategory = typeof FINDING_CATEGORIES[number];
export type DeviceRolePreset = "Essential" | "NetworkEdge" | "WebServer" | "ContainerHost" | "CloudControlPlane";
export type TelemetryVendor = "linux" | "mikrotik" | "fortigate" | "pfsense" | "cisco" | "paloalto" | "juniper" | "windows" | "docker" | "kubernetes" | "aws" | "azure";
export type VendorFindingRule = { id: string; title: string; category: FindingCategory; severity: "low" | "medium" | "high" | "critical"; confidence: number; eventPattern?: RegExp; threshold?: number; windowMinutes?: number; snapshotPath?: string; snapshotTest?: "truthy" | "enabled" | "inactive" | "public"; whyItMatters: string; recommendedIntent: string; mitreTags?: string[] };
export type VendorTelemetryProfile = { vendorId: TelemetryVendor; vendorName: string; roles: DeviceRolePreset[]; liveSources: string[]; snapshotSources: string[]; findingRules: VendorFindingRule[]; suppressionRules: Array<{ id: string; pattern: RegExp; reason: string }>; recommendedRemediationIntents: string[]; implemented: "implemented" | "scaffolded" };

const rule = (id: string, title: string, category: FindingCategory, severity: VendorFindingRule["severity"], eventPattern: RegExp, recommendedIntent: string, threshold = 1, mitreTags: string[] = []): VendorFindingRule => ({ id, title, category, severity, confidence: threshold > 1 ? .9 : .86, eventPattern, threshold, windowMinutes: 5, whyItMatters: `${title} can indicate security exposure, compromise, or loss of control.`, recommendedIntent, mitreTags });
const noise = [{ id: "routine-health", pattern: /health.?check|keepalive|session closed normally|cron.*session (opened|closed)/i, reason: "Routine health/session noise" }, { id: "debug", pattern: /\bdebug\b.*(?:poll|heartbeat|metrics)/i, reason: "Low-value debug telemetry" }];
const p = (vendorId: TelemetryVendor, vendorName: string, liveSources: string[], snapshotSources: string[], findingRules: VendorFindingRule[], implemented: VendorTelemetryProfile["implemented"] = "scaffolded"): VendorTelemetryProfile => ({ vendorId, vendorName, roles: ["Essential", "NetworkEdge", "WebServer", "ContainerHost", "CloudControlPlane"], liveSources, snapshotSources, findingRules, suppressionRules: noise, recommendedRemediationIntents: [...new Set(findingRules.map(x => x.recommendedIntent))], implemented });

export const VENDOR_TELEMETRY_PROFILES: Record<TelemetryVendor, VendorTelemetryProfile> = {
  linux: p("linux", "Linux", ["auth", "system", "kernel", "firewall", "nginx", "docker"], ["ssh_config", "listeners", "firewall", "security_tools", "containers"], [
    rule("ssh-failure-burst", "Repeated SSH authentication failures", "auth", "high", /(?:sshd|pam_unix\(sshd:auth\)).*(?:failed password|invalid user|authentication failure)|failed password for|invalid user .* from/i, "block_source_ip_temporary", 5, ["T1110"]),
    rule("ssh-success-after-failures", "SSH success after authentication failures", "auth", "critical", /accepted (?:password|publickey).*after.*fail|success_after_failures/i, "linux_investigate_login", 1, ["T1078"]),
    rule("sudo-denied-burst", "Repeated denied sudo attempts", "privilege", "high", /sudo(?:\[\d+\])?:.*(?:not in the sudoers|permission denied|authentication failure|incorrect password)/i, "linux_review_privilege", 3, ["T1548"]),
    rule("nginx-5xx-burst", "Nginx 5xx response burst", "web_app", "high", /(?:nginx|http).*(?: 5\d\d |status[=:]5\d\d)/i, "linux_investigate_web_service", 10),
    rule("docker-restart-oom", "Docker container restart or OOM", "container_runtime", "high", /docker.*(?:oom|out of memory|restarting|restart loop|killed)/i, "docker_investigate_container", 2, ["T1496"]),
    { id: "ssh-password-auth", title: "SSH password authentication is enabled", category: "posture", severity: "high", confidence: .98, snapshotPath: "ssh.passwordAuthentication", snapshotTest: "enabled", whyItMatters: "Password SSH expands credential-attack risk.", recommendedIntent: "linux_harden_ssh", mitreTags: ["T1110"] },
    { id: "ssh-root-login", title: "Direct root SSH login is enabled", category: "privilege", severity: "high", confidence: .98, snapshotPath: "ssh.permitRootLogin", snapshotTest: "enabled", whyItMatters: "A compromised login immediately gains full control.", recommendedIntent: "linux_harden_ssh", mitreTags: ["T1078"] },
    { id: "ssh-public", title: "SSH is exposed on a wildcard/public interface", category: "management_exposure", severity: "high", confidence: .94, snapshotPath: "network.publicExposureSummary", snapshotTest: "public", whyItMatters: "Internet-reachable management attracts automated attacks.", recommendedIntent: "linux_review_exposed_port" },
    { id: "fail2ban-inactive", title: "Fail2ban inactive while SSH is exposed", category: "posture", severity: "medium", confidence: .9, snapshotPath: "securityTools.fail2ban", snapshotTest: "inactive", whyItMatters: "Repeated authentication attacks are not locally throttled.", recommendedIntent: "linux_review_fail2ban" },
    { id: "auditd-inactive", title: "Auditd inactive or unavailable", category: "log_tamper", severity: "medium", confidence: .9, snapshotPath: "securityTools.auditd", snapshotTest: "inactive", whyItMatters: "Important security activity may lack an audit trail.", recommendedIntent: "linux_enable_auditd", mitreTags: ["T1562.002"] }
  ], "implemented"),
  mikrotik: p("mikrotik", "MikroTik RouterOS", ["system", "account", "firewall", "ipsec", "l2tp"], ["ip_services", "firewall_filter", "nat", "users", "vpn"], [
    rule("management-exposed", "Management service exposed", "management_exposure", "high", /(?:ssh|winbox|webfig|www|api).*(?:wan|public|0\.0\.0\.0\/0|available from any)/i, "mikrotik_restrict_management"), rule("insecure-services", "Insecure management service enabled", "management_exposure", "high", /(?:telnet|ftp|www|api).*(?:enabled|running)/i, "mikrotik_disable_service"), rule("login-failures", "Repeated RouterOS login failures", "auth", "high", /login failure|authentication failed|invalid user/i, "mikrotik_block_ip_temporary", 5, ["T1110"]), rule("risky-dstnat", "Risky public dstnat exposure", "firewall_vpn", "high", /dstnat.*(?:0\.0\.0\.0\/0|in-interface.*wan|public)/i, "mikrotik_review_dstnat"), rule("vpn-failures", "VPN/IPsec/L2TP failure burst", "firewall_vpn", "high", /(?:ipsec|l2tp|vpn).*(?:fail|timeout|no proposal|disconnected)/i, "mikrotik_investigate_vpn", 3), rule("input-drop-burst", "Firewall input drop burst", "deny_drop_burst", "medium", /firewall.*input.*(?:drop|deny)/i, "mikrotik_investigate_firewall", 20), rule("privileged-change", "Privileged user, service, or configuration change", "config_change", "high", /(?:user|service|configuration|config).*(?:added|changed|removed|enabled|disabled)/i, "mikrotik_review_config_change", 1, ["T1098"])
  ], "implemented"),
  fortigate: p("fortigate", "FortiGate", ["event", "traffic", "utm", "vpn"], ["system", "admins", "interfaces", "policies", "vip", "local_in", "vpn"], [rule("admin-fail", "Admin login failures", "auth", "high", /admin.*login.*fail/i, "fortigate_investigate_admin", 5), rule("management-exposed", "Management plane exposed or trusted hosts missing", "management_exposure", "high", /admin.*(?:trusted host missing|https|ssh).*(?:wan|public)/i, "fortigate_restrict_admin"), rule("local-in-exposure", "Local-in or policy exposure", "firewall_vpn", "high", /local-?in|policy.*(?:all|0\.0\.0\.0\/0)/i, "fortigate_review_policy"), rule("vip-risk", "Risky VIP/NAT publish", "firewall_vpn", "high", /vip|virtual ip.*(?:wan|any|public)/i, "fortigate_review_vip"), rule("sslvpn-fail", "SSL-VPN authentication failures", "auth", "high", /ssl.?vpn.*auth.*fail/i, "fortigate_investigate_vpn", 5), rule("ipsec-flap", "IPsec tunnel failure or flap", "service_health", "high", /ipsec.*(?:down|fail|flap|phase [12].*fail)/i, "fortigate_investigate_vpn", 3), rule("utm-threat", "Severe UTM threat event", "malware_threat", "critical", /(?:utm|av|ips|malware).*(?:critical|severe|blocked)/i, "fortigate_contain_threat", 1, ["T1204"]), rule("admin-change", "Configuration revision or admin change", "config_change", "high", /config.*(?:revision|change)|admin.*(?:add|delete|change)/i, "fortigate_review_config_change")], "implemented"),
  pfsense: p("pfsense", "pfSense", ["auth", "filterlog", "openvpn", "ipsec", "sshguard"], ["webgui", "ssh", "rules", "nat", "vpn", "updates"], [rule("auth-fail", "WebGUI/SSH authentication failures", "auth", "high", /(?:webgui|sshd).*fail/i, "pfsense_investigate_auth", 5), rule("wan-management", "WebGUI/SSH exposed on WAN", "management_exposure", "high", /(?:webgui|ssh).*(?:wan|public)/i, "pfsense_restrict_management"), rule("sshguard-spike", "sshguard block spike", "deny_drop_burst", "medium", /sshguard.*block/i, "pfsense_investigate_auth", 10), rule("deny-burst", "Firewall deny burst", "deny_drop_burst", "medium", /filterlog.*(?:block|deny)/i, "pfsense_investigate_firewall", 20), rule("nat-risk", "Risky NAT/port forward", "firewall_vpn", "high", /(?:nat|port forward).*(?:wan|any|public)/i, "pfsense_review_nat"), rule("vpn-fail", "OpenVPN/IPsec failures", "service_health", "high", /(?:openvpn|ipsec).*(?:fail|down|timeout)/i, "pfsense_investigate_vpn", 3), rule("update-posture", "Security update/advisory requires review", "posture", "medium", /update|advisory.*(?:available|security|vulnerable)/i, "pfsense_review_updates")], "implemented"),
  cisco: p("cisco", "Cisco", ["aaa", "syslog", "acl", "vpn"], ["version", "aaa", "vty", "acls", "snmp"], [rule("aaa-fail", "AAA login failure burst", "auth", "high", /aaa|login.*fail/i, "cisco_investigate_aaa", 5), rule("telnet", "Telnet management enabled", "management_exposure", "high", /transport input.*telnet/i, "cisco_disable_telnet"), rule("config-change", "Configuration change", "config_change", "high", /configured from|config.*changed/i, "cisco_review_config"), rule("acl-deny", "ACL deny burst", "deny_drop_burst", "medium", /access-list.*denied|acl.*drop/i, "cisco_investigate_acl", 20), rule("vpn-down", "VPN/tunnel failure", "service_health", "high", /tunnel|ike|ipsec.*(?:down|fail)/i, "cisco_investigate_vpn", 3)]),
  paloalto: p("paloalto", "Palo Alto Networks", ["system", "traffic", "threat", "globalprotect"], ["admins", "management", "security_rules", "nat", "profiles"], [rule("admin-fail", "Administrator login failures", "auth", "high", /admin.*auth.*fail/i, "paloalto_investigate_admin", 5), rule("mgmt-exposure", "Management interface exposed", "management_exposure", "high", /management.*(?:public|untrusted|any)/i, "paloalto_restrict_management"), rule("threat", "Critical threat prevention event", "malware_threat", "critical", /threat.*(?:critical|high)|wildfire.*malicious/i, "paloalto_contain_threat"), rule("gp-fail", "GlobalProtect authentication failures", "auth", "high", /globalprotect.*fail/i, "paloalto_investigate_globalprotect", 5), rule("commit", "Privileged commit/config change", "config_change", "high", /commit|configuration.*changed/i, "paloalto_review_commit")]),
  juniper: p("juniper", "Juniper", ["auth", "messages", "rt_flow", "ipsec"], ["system", "login", "services", "firewall", "security_policies"], [rule("auth-fail", "Management authentication failures", "auth", "high", /login.*fail|authentication failed/i, "juniper_investigate_auth", 5), rule("root-login", "Root remote login enabled", "privilege", "high", /root-login.*allow/i, "juniper_restrict_root"), rule("config-change", "Configuration committed", "config_change", "high", /commit complete|configuration changed/i, "juniper_review_commit"), rule("deny-burst", "Firewall deny burst", "deny_drop_burst", "medium", /rt_flow.*deny|firewall.*discard/i, "juniper_investigate_firewall", 20), rule("ipsec-fail", "IPsec failure", "service_health", "high", /ike|ipsec.*(?:fail|down)/i, "juniper_investigate_vpn", 3)]),
  windows: p("windows", "Windows", ["Security", "System", "PowerShell", "Defender"], ["audit_policy", "firewall", "rdp", "defender", "local_admins"], [rule("login-fail", "Windows logon failure burst", "auth", "high", /event.?id.?4625|logon failure/i, "windows_investigate_logon", 5, ["T1110"]), rule("admin-member", "Privileged group membership changed", "privilege", "high", /event.?id.?(4728|4732|4756)/i, "windows_review_privilege", 1, ["T1098"]), rule("powershell", "Suspicious PowerShell execution", "malware_threat", "high", /powershell.*(?:encodedcommand|downloadstring|invoke-expression)/i, "windows_investigate_powershell", 1, ["T1059.001"]), rule("defender", "Defender threat detected", "malware_threat", "critical", /defender.*(?:threat|malware).*detected/i, "windows_contain_threat"), rule("log-clear", "Windows event log cleared", "log_tamper", "critical", /event.?id.?1102|audit log.*cleared/i, "windows_investigate_log_clear", 1, ["T1070.001"])]),
  docker: p("docker", "Docker", ["daemon", "events", "container_logs"], ["containers", "images", "networks", "daemon_config"], [rule("oom", "Container OOM/restart loop", "container_runtime", "high", /oom|restart(?:ing)? loop/i, "docker_investigate_container", 2), rule("privileged", "Privileged container started", "container_runtime", "critical", /privileged.*(?:true|container)/i, "docker_restrict_container"), rule("socket", "Docker socket exposed", "management_exposure", "critical", /docker\.sock|tcp:\/\/0\.0\.0\.0:2375/i, "docker_restrict_daemon"), rule("image", "Untrusted image pulled", "posture", "high", /pull.*(?:latest|untrusted|unsigned)/i, "docker_review_image"), rule("exec", "Interactive exec into container", "privilege", "medium", /exec_(?:create|start)|docker exec/i, "docker_review_exec")]),
  kubernetes: p("kubernetes", "Kubernetes", ["audit", "events", "control_plane", "runtime"], ["rbac", "pods", "services", "network_policies", "api_server"], [rule("anonymous", "Anonymous API access", "management_exposure", "critical", /system:anonymous|anonymous-auth.*true/i, "k8s_disable_anonymous"), rule("cluster-admin", "Cluster-admin binding changed", "privilege", "critical", /clusterrolebinding.*cluster-admin/i, "k8s_review_rbac", 1, ["T1098"]), rule("privileged-pod", "Privileged pod created", "container_runtime", "critical", /privileged.*true|hostPID.*true/i, "k8s_restrict_workload"), rule("secret", "Secret accessed unusually", "cloud_control_plane", "high", /(?:get|list).*secrets/i, "k8s_investigate_secret_access", 3), rule("pod-crash", "Pod crash/OOM loop", "service_health", "high", /CrashLoopBackOff|OOMKilled/i, "k8s_investigate_workload", 2)]),
  aws: p("aws", "Amazon Web Services", ["cloudtrail", "guardduty", "vpc_flow", "config"], ["iam", "cloudtrail", "security_groups", "s3", "organizations"], [rule("root", "AWS root account activity", "cloud_control_plane", "critical", /root.*(?:ConsoleLogin|eventName)/i, "aws_investigate_root", 1, ["T1078.004"]), rule("iam", "IAM privilege escalation change", "privilege", "critical", /Attach.*Policy|Put.*Policy|CreateAccessKey/i, "aws_review_iam"), rule("cloudtrail", "CloudTrail disabled or changed", "log_tamper", "critical", /StopLogging|DeleteTrail|UpdateTrail/i, "aws_restore_cloudtrail", 1, ["T1562.008"]), rule("sg-open", "Security group opened publicly", "management_exposure", "high", /AuthorizeSecurityGroupIngress.*0\.0\.0\.0\/0/i, "aws_restrict_security_group"), rule("guardduty", "High-severity GuardDuty finding", "malware_threat", "critical", /guardduty.*(?:high|critical)/i, "aws_contain_threat")]),
  azure: p("azure", "Microsoft Azure", ["activity", "entra_signin", "defender", "nsg_flow"], ["rbac", "nsg", "diagnostics", "key_vault", "policy"], [rule("signin", "Risky Azure sign-in", "auth", "high", /risky.*sign-in|signin.*failure/i, "azure_investigate_signin", 3), rule("role", "Privileged Azure role assignment", "privilege", "critical", /role assignment.*(?:owner|contributor|global administrator)/i, "azure_review_rbac"), rule("diagnostic", "Diagnostic logging disabled", "log_tamper", "high", /diagnostic.*(?:disabled|deleted)/i, "azure_restore_diagnostics"), rule("nsg", "NSG exposes management publicly", "management_exposure", "high", /nsg.*0\.0\.0\.0\/0.*(?:22|3389)/i, "azure_restrict_nsg"), rule("defender", "Defender for Cloud severe alert", "malware_threat", "critical", /defender.*(?:high|critical)/i, "azure_contain_threat")])
};

export function normalizeTelemetryVendor(value: unknown): TelemetryVendor | null { const v = String(value ?? "").toLowerCase().replace(/[^a-z0-9]/g, ""); if (v.includes("mikrotik") || v.includes("routeros")) return "mikrotik"; if (v.includes("forti")) return "fortigate"; if (v.includes("pfsense")) return "pfsense"; if (v.includes("palo")) return "paloalto"; if (v.includes("juniper")) return "juniper"; if (v.includes("windows")) return "windows"; if (v.includes("kubernetes") || v === "k8s") return "kubernetes"; return (Object.keys(VENDOR_TELEMETRY_PROFILES) as TelemetryVendor[]).find(x => v.includes(x)) ?? null; }
export function getVendorTelemetryProfile(vendor: unknown, type?: unknown) { const id = normalizeTelemetryVendor(vendor) ?? normalizeTelemetryVendor(type); return id ? VENDOR_TELEMETRY_PROFILES[id] : null; }
