import { ActionType, DeviceType } from "@prisma/client";
import { mikroTikSupportedActions, validateMikroTikAction } from "../../actions/mikrotik-action-catalog.js";
import type { PlannerInput, VendorCommandPlan, VendorPlanner } from "../types.js";
import { customPlanFromParameters } from "../../ai/custom-action-plan.js";

export const mikrotikPlanner: VendorPlanner = {
  vendor: "mikrotik",
  supportedActions: [...mikroTikSupportedActions(), ActionType.custom_vendor_action],
  supports(device) {
    return device?.type === DeviceType.mikrotik || String(device?.vendor ?? "").toLowerCase().includes("mikrotik");
  },
  plan(input: PlannerInput): VendorCommandPlan {
    if (input.actionType === ActionType.custom_vendor_action) {
      const customPlan = customPlanFromParameters(input.parameters);
      return {
        status: customPlan?.vendor === "mikrotik" ? "planned" : "unsupported",
        vendor: "mikrotik",
        deviceId: input.device?.id ?? null,
        actionType: input.actionType,
        transport: customPlan?.vendor === "mikrotik" ? "ssh" : "manual",
        commands: customPlan ? [...customPlan.orderedCommands, ...customPlan.verificationCommands] : [],
        apiCalls: [],
        warnings: ["Custom MikroTik plan generated by AI and normalized by backend; connector dry-run performs the executable preview."],
        rollbackSteps: customPlan?.rollbackGuidance ?? [],
        riskLevel: customPlan?.riskLevel ?? input.riskLevel,
        requiresApproval: true,
        unsupportedReason: customPlan?.vendor === "mikrotik" ? undefined : "MikroTik custom command plan is missing or targets another vendor."
      };
    }
    const validation = validateMikroTikAction({
      actionType: input.actionType,
      parametersJson: input.parameters,
      riskLevel: input.riskLevel
    });

    if (!validation.valid) {
      return {
        status: "needs_clarification",
        vendor: "mikrotik",
        deviceId: input.device?.id ?? null,
        actionType: input.actionType,
        transport: "ssh",
        commands: [],
        apiCalls: [],
        warnings: validation.warnings,
        rollbackSteps: [],
        riskLevel: validation.riskLevel,
        requiresApproval: true,
        missingFields: validation.errors,
        questions: validation.errors
      };
    }

    return {
      status: "planned",
      vendor: "mikrotik",
      deviceId: input.device?.id ?? null,
      actionType: input.actionType,
      transport: "ssh",
      commands: validation.commandSpecs.map((spec) => spec.command),
      apiCalls: [],
      warnings: validation.warnings,
      rollbackSteps: validation.commandSpecs.flatMap((spec) => spec.rollbackSteps),
      riskLevel: validation.riskLevel,
      requiresApproval: validation.commandSpecs.some((spec) => spec.write),
      unsupportedReason: undefined
    };
  }
};
